INSERT INTO interface_translations(language_code,translation_key,translation_value) VALUES
('tm','cpanel.media.created','Bukja döredildi.'),('ru','cpanel.media.created','Папка создана.'),('en','cpanel.media.created','Folder created.'),
('tm','cpanel.media.renamed','Ady üýtgedildi.'),('ru','cpanel.media.renamed','Переименовано.'),('en','cpanel.media.renamed','Renamed successfully.'),
('tm','cpanel.media.deleted','Pozuldy.'),('ru','cpanel.media.deleted','Удалено.'),('en','cpanel.media.deleted','Deleted successfully.'),
('tm','cpanel.media.conflict','Bu at bilen faýl ýa-da bukja eýýäm bar.'),('ru','cpanel.media.conflict','Файл или папка с таким именем уже существует.'),('en','cpanel.media.conflict','A file or folder with this name already exists.'),
('tm','cpanel.media.invalidName','Bir dogry faýl ýa-da bukja adyny giriziň. Ýol bölüjiler we gizlin atlar rugsat berilmeýär.'),('ru','cpanel.media.invalidName','Укажите допустимое имя. Разделители пути и скрытые имена запрещены.'),('en','cpanel.media.invalidName','Enter a valid name. Path separators and hidden names are not allowed.'),
('tm','cpanel.media.invalidPath','Media ýoly nädogry ýa-da elýeterli däl.'),('ru','cpanel.media.invalidPath','Путь медиа недопустим или недоступен.'),('en','cpanel.media.invalidPath','The media path is invalid or unavailable.'),
('tm','cpanel.media.rootProtected','Media köküniň adyny üýtgedip ýa-da ony pozup bolmaýar.'),('ru','cpanel.media.rootProtected','Корень медиа нельзя переименовать или удалить.'),('en','cpanel.media.rootProtected','Media root cannot be renamed or deleted.'),
('tm','cpanel.media.cacheProtected','Bu ýol wagtlaýyn ýükleme tokenleri üçin niýetlenendir.'),('ru','cpanel.media.cacheProtected','Этот путь зарезервирован для временных токенов загрузки.'),('en','cpanel.media.cacheProtected','This path is reserved for temporary upload tokens.'),
('tm','cpanel.media.recursiveConfirm','Bukjany içindäki ähli zatlar bilen hemişelik pozmagy tassyklaýaryn.'),('ru','cpanel.media.recursiveConfirm','Подтверждаю безвозвратное удаление папки со всем содержимым.'),('en','cpanel.media.recursiveConfirm','I confirm permanent deletion of this folder and all its contents.'),
('tm','cpanel.media.nonEmpty','Bu bukjada faýllar ýa-da içki bukjalar bar. Ähli mazmun hemişelik pozular.'),('ru','cpanel.media.nonEmpty','Папка содержит файлы или вложенные папки. Всё содержимое будет удалено безвозвратно.'),('en','cpanel.media.nonEmpty','This folder contains files or subfolders. All contents will be permanently deleted.'),
('tm','cpanel.media.uploadPolicy','Islendik görnüşdäki faýl: her faýl üçin iň köp 10 MB (10 485 760 baýt).'),('ru','cpanel.media.uploadPolicy','Любой тип файла: максимум 10 МБ (10 485 760 байт) на файл.'),('en','cpanel.media.uploadPolicy','Any file type: up to 10 MB (10,485,760 bytes) per file.'),
('tm','cpanel.media.working','Ýerine ýetirilýär…'),('ru','cpanel.media.working','Выполняется…'),('en','cpanel.media.working','Working…');
INSERT INTO interface_translations(language_code,translation_key,translation_value) VALUES
('tm','cpanel.media.directUploaded','Faýl şu bukja ýüklendi.'),('ru','cpanel.media.directUploaded','Файл загружен в текущую папку.'),('en','cpanel.media.directUploaded','File uploaded to the current folder.');
