-- Interface localization only. Brand/media relationships remain UI mocks.
INSERT INTO interface_translations(language_code,translation_key,translation_value) VALUES
('tm','cpanel.brands.mainImage','Esasy surat'),
('ru','cpanel.brands.mainImage','Главное изображение'),
('en','cpanel.brands.mainImage','Main Image'),
('tm','cpanel.brands.emptyMain','Esasy surat saýlanmady'),
('ru','cpanel.brands.emptyMain','Главное изображение не выбрано'),
('en','cpanel.brands.emptyMain','No main image selected'),
('tm','cpanel.brands.removeMain','Esasy suraty aýyrmak'),
('ru','cpanel.brands.removeMain','Убрать главное изображение'),
('en','cpanel.brands.removeMain','Remove Main Image'),
('tm','cpanel.brands.mainLocked','Esasy suraty saýlamak üçin ilki brendi dörediň.'),
('ru','cpanel.brands.mainLocked','Сначала создайте бренд, чтобы выбрать главное изображение.'),
('en','cpanel.brands.mainLocked','Create the Brand first to select its Main Image.'),
('tm','cpanel.media.selectMedia','Mediýa saýlamak'),
('ru','cpanel.media.selectMedia','Выбрать медиа'),
('en','cpanel.media.selectMedia','Select Media'),
('tm','cpanel.media.changeMedia','Mediýany çalyşmak'),
('ru','cpanel.media.changeMedia','Заменить медиа'),
('en','cpanel.media.changeMedia','Change Media'),
('tm','cpanel.media.pickerTitle','Mediýa saýlawy'),
('ru','cpanel.media.pickerTitle','Выбор медиа'),
('en','cpanel.media.pickerTitle','Media Picker'),
('tm','cpanel.media.pickerUploadNotice','Ýüklenen faýllar saýlaw ýatyrylsa-da Mediýada saklanýar.'),
('ru','cpanel.media.pickerUploadNotice','Загруженные файлы остаются в Медиа, даже если отменить выбор.'),
('en','cpanel.media.pickerUploadNotice','Uploaded files remain in Media even if you cancel selection.'),
('tm','cpanel.media.pickerSelected','Saýlanan'),
('ru','cpanel.media.pickerSelected','Выбрано'),
('en','cpanel.media.pickerSelected','Selected'),
('tm','cpanel.media.pickerAlreadyAdded','Galereýa eýýäm goşuldy'),
('ru','cpanel.media.pickerAlreadyAdded','Уже добавлено в галерею'),
('en','cpanel.media.pickerAlreadyAdded','Already in Gallery');
