INSERT INTO interface_translations(language_code,translation_key,translation_value) VALUES
('tm','cpanel.autocomplete.clear','Saýlawy arassala'),
('ru','cpanel.autocomplete.clear','Очистить выбор'),
('en','cpanel.autocomplete.clear','Clear selection'),
('tm','cpanel.autocomplete.search','Gözlemek üçin ýazyň…'),
('ru','cpanel.autocomplete.search','Введите текст для поиска…'),
('en','cpanel.autocomplete.search','Type to search…'),
('tm','cpanel.autocomplete.retry','Täzeden synanyş'),
('ru','cpanel.autocomplete.retry','Повторить'),
('en','cpanel.autocomplete.retry','Retry'),
('tm','cpanel.autocomplete.more','Ýene görkez'),
('ru','cpanel.autocomplete.more','Показать ещё'),
('en','cpanel.autocomplete.more','Load more'),
('tm','cpanel.autocomplete.empty','Netije tapylmady'),
('ru','cpanel.autocomplete.empty','Ничего не найдено'),
('en','cpanel.autocomplete.empty','No results'),
('tm','cpanel.autocomplete.failed','Ýükläp bolmady'),
('ru','cpanel.autocomplete.failed','Не удалось загрузить'),
('en','cpanel.autocomplete.failed','Failed to load');
