INSERT INTO interface_translations(language_code,translation_key,translation_value) VALUES
('tm','cpanel.productCreate.create','Storefront önümini döret'),
('ru','cpanel.productCreate.create','Создать товар витрины'),
('en','cpanel.productCreate.create','Create Storefront Product'),
('tm','cpanel.productCreate.vendorFirst','Ilki üpjün edijini saýlaň'),
('ru','cpanel.productCreate.vendorFirst','Сначала выберите поставщика'),
('en','cpanel.productCreate.vendorFirst','Select Vendor first'),
('tm','cpanel.productCreate.existing','Bu çeşme önümine eýýäm {count} sany storefront önümi baglanan. Şol çeşmeden ýene bir önüm döredip bilersiňiz.'),
('ru','cpanel.productCreate.existing','С этим исходным товаром уже связано товаров витрины: {count}. Можно создать ещё один товар из того же источника.'),
('en','cpanel.productCreate.existing','This source already has {count} storefront products. You can create another product from the same source.'),
('tm','cpanel.productCreate.name','Önümiň ady'),
('ru','cpanel.productCreate.name','Название товара'),
('en','cpanel.productCreate.name','Product Name'),
('tm','cpanel.productCreate.placeholder','Döretmek ädimi görkezildi. Önümiň goşmaça sazlamalary Edit interfeýsinde elýeterli bolar.'),
('ru','cpanel.productCreate.placeholder','Переход после создания показан. Дальнейшие настройки товара будут доступны в интерфейсе редактирования.'),
('en','cpanel.productCreate.placeholder','Creation preview complete. Further configuration will be available in the Product Edit interface.'),
('tm','cpanel.productCreate.preview','Interfeýsiň synagy: önüm maglumatlary maglumatlar bazasyna ýazylmaýar.'),
('ru','cpanel.productCreate.preview','Предпросмотр интерфейса: данные товара не сохраняются в базе.'),
('en','cpanel.productCreate.preview','Interface preview: Product data is not saved to the database.'),
('tm','cpanel.productCreate.back','Yza'),
('ru','cpanel.productCreate.back','Назад'),
('en','cpanel.productCreate.back','Back');
