INSERT INTO interface_translations(language_code,translation_key,translation_value) VALUES
('tm','cpanel.attachments.attach','Önüm goşmak'),
('ru','cpanel.attachments.attach','Прикрепить товар'),
('en','cpanel.attachments.attach','Attach Product'),
('tm','cpanel.attachments.search','Önüm gözle...'),
('ru','cpanel.attachments.search','Поиск товара...'),
('en','cpanel.attachments.search','Search Product...'),
('tm','cpanel.attachments.detach','Önümi aýyrmak'),
('ru','cpanel.attachments.detach','Открепить товар'),
('en','cpanel.attachments.detach','Detach Product'),
('tm','cpanel.attachments.move','Önümi geçirmek'),
('ru','cpanel.attachments.move','Переместить товар'),
('en','cpanel.attachments.move','Move Product'),
('tm','cpanel.attachments.current','Önüm häzir şu ýere degişli'),
('ru','cpanel.attachments.current','Товар сейчас прикреплён к'),
('en','cpanel.attachments.current','Product is currently attached to'),
('tm','cpanel.attachments.destination','Önümi şu ýere geçirmek'),
('ru','cpanel.attachments.destination','Переместить товар в'),
('en','cpanel.attachments.destination','Move this Product to'),
('tm','cpanel.attachments.attached','Önüm goşuldy.'),
('ru','cpanel.attachments.attached','Товар прикреплён.'),
('en','cpanel.attachments.attached','Product attached.'),
('tm','cpanel.attachments.detached','Önüm aýryldy.'),
('ru','cpanel.attachments.detached','Товар откреплён.'),
('en','cpanel.attachments.detached','Product detached.');
