INSERT INTO interface_translations(language_code,translation_key,translation_value) VALUES
('tm','cpanel.bulkDrafts.title','Önüm garalamalaryny döretmek'),
('ru','cpanel.bulkDrafts.title','Создать черновики товаров'),
('en','cpanel.bulkDrafts.title','Create Product Drafts'),
('tm','cpanel.bulkDrafts.matching','Gabat gelýän çeşme önümleri'),
('ru','cpanel.bulkDrafts.matching','Найдено исходных товаров'),
('en','cpanel.bulkDrafts.matching','Matching Source Products'),
('tm','cpanel.bulkDrafts.selected','Saýlanan'),
('ru','cpanel.bulkDrafts.selected','Выбрано'),
('en','cpanel.bulkDrafts.selected','Selected'),
('tm','cpanel.bulkDrafts.prefix','Önümiň adynyň öň goşulmasy'),
('ru','cpanel.bulkDrafts.prefix','Префикс названия товара'),
('en','cpanel.bulkDrafts.prefix','Product Name Prefix'),
('tm','cpanel.bulkDrafts.all','Ählisini saýlamak'),
('ru','cpanel.bulkDrafts.all','Выбрать все'),
('en','cpanel.bulkDrafts.all','Select All'),
('tm','cpanel.bulkDrafts.clear','Saýlawy arassalamak'),
('ru','cpanel.bulkDrafts.clear','Снять выбор'),
('en','cpanel.bulkDrafts.clear','Clear Selection'),
('tm','cpanel.bulkDrafts.existing','Bar bolan vitrina önümleri'),
('ru','cpanel.bulkDrafts.existing','Существующие товары витрины'),
('en','cpanel.bulkDrafts.existing','Existing storefront Products'),
('tm','cpanel.bulkDrafts.create','{count} önüm döretmek'),
('ru','cpanel.bulkDrafts.create','Создать товары: {count}'),
('en','cpanel.bulkDrafts.create','Create {count} Products'),
('tm','cpanel.bulkDrafts.creating','Önüm garalamalary döredilýär...'),
('ru','cpanel.bulkDrafts.creating','Создание черновиков товаров...'),
('en','cpanel.bulkDrafts.creating','Creating Product drafts...'),
('tm','cpanel.bulkDrafts.created','Döredildi'),
('ru','cpanel.bulkDrafts.created','Создано'),
('en','cpanel.bulkDrafts.created','Created'),
('tm','cpanel.bulkDrafts.failed','Şowsuz'),
('ru','cpanel.bulkDrafts.failed','Не удалось'),
('en','cpanel.bulkDrafts.failed','Failed'),
('tm','cpanel.bulkDrafts.complete','Önüm garalamalary döredildi.'),
('ru','cpanel.bulkDrafts.complete','Черновики товаров созданы.'),
('en','cpanel.bulkDrafts.complete','Product drafts created successfully.'),
('tm','cpanel.bulkDrafts.uncertain','Netijäni önümler sanawyndan barlaň. Bu amaly gaýtadan döretmäň.'),
('ru','cpanel.bulkDrafts.uncertain','Проверьте результат в списке товаров. Не создавайте эту операцию повторно.'),
('en','cpanel.bulkDrafts.uncertain','Verify the result in the Products list. Do not recreate this operation.'),
('tm','cpanel.bulkDrafts.expired','Amal tapylmady ýa-da möhleti gutardy. Gaýtadan döretmezden öň önümler sanawyny barlaň.'),
('ru','cpanel.bulkDrafts.expired','Операция не найдена или истекла. Перед повторным созданием проверьте список товаров.'),
('en','cpanel.bulkDrafts.expired','Operation unavailable or expired. Check the Products list before creating again.');
