INSERT INTO interface_translations(language_code,translation_key,translation_value) VALUES
('tm','cpanel.productBrowser.storefront','Witrinadaky ýagdaý'),
('ru','cpanel.productBrowser.storefront','Статус на витрине'),
('en','cpanel.productBrowser.storefront','Storefront status'),
('tm','cpanel.productBrowser.effectiveHidden','Witrinada gizlenen'),
('ru','cpanel.productBrowser.effectiveHidden','Скрыт на витрине'),
('en','cpanel.productBrowser.effectiveHidden','Effectively hidden'),
('tm','cpanel.productBrowser.noBrand','Brendsiz'),
('ru','cpanel.productBrowser.noBrand','Без бренда'),
('en','cpanel.productBrowser.noBrand','No Brand'),
('tm','cpanel.productBrowser.noCategory','Kategoriýasyz'),
('ru','cpanel.productBrowser.noCategory','Без категории'),
('en','cpanel.productBrowser.noCategory','No Category'),
('tm','cpanel.productBrowser.hasDiscount','Arzanladyşy bar'),
('ru','cpanel.productBrowser.hasDiscount','Есть скидки'),
('en','cpanel.productBrowser.hasDiscount','Has Discounts'),
('tm','cpanel.productBrowser.noDiscount','Arzanladyş ýok'),
('ru','cpanel.productBrowser.noDiscount','Без скидок'),
('en','cpanel.productBrowser.noDiscount','No Discounts'),
('tm','cpanel.productBrowser.quantity','Mukdary görkezmek'),
('ru','cpanel.productBrowser.quantity','Показывать количество'),
('en','cpanel.productBrowser.quantity','Show Quantity'),
('tm','cpanel.productBrowser.yes','Hawa'),
('ru','cpanel.productBrowser.yes','Да'),
('en','cpanel.productBrowser.yes','Yes'),
('tm','cpanel.productBrowser.no','Ýok'),
('ru','cpanel.productBrowser.no','Нет'),
('en','cpanel.productBrowser.no','No'),
('tm','cpanel.productBrowser.count','Önümler: {count}'),
('ru','cpanel.productBrowser.count','Товаров: {count}'),
('en','cpanel.productBrowser.count','Products: {count}')
ON CONFLICT(language_code,translation_key) DO UPDATE SET translation_value=EXCLUDED.translation_value;
