import {test,expect,type Page} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {createServer} from 'node:net';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
test.use({actionTimeout:10000});
const folder='brands-live-'+randomUUID(),root=path.resolve('.test-media',folder),pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8x8AAAAASUVORK5CYII=','base64');
test.beforeAll(async()=>{await mkdir(root,{recursive:true});for(const name of ['a.png','b.png','c.png'])await writeFile(path.join(root,name),pixel);await writeFile(path.join(root,'text.txt'),'not image');});
test.afterAll(async()=>{await rm(root,{recursive:true,force:true});});
async function login(context:any,baseURL:string){const user=await bootstrapSuperuser({name:'Brands activation test',email:randomUUID()+'@example.invalid',password:randomUUID()});const session=await sessions.create(user.id);await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL}]);return {id:user.id,csrf:session.session.csrf_token};}
async function cleanup(page:Page,id:string){await page.goto('about:blank').catch(()=>{});await pool.query('DELETE FROM brand_media WHERE brand_id IN(SELECT id FROM brands WHERE created_by=$1)',[id]);await pool.query('DELETE FROM brand_translations WHERE brand_id IN(SELECT id FROM brands WHERE created_by=$1)',[id]);await pool.query('DELETE FROM brands WHERE created_by=$1',[id]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[id]);}
async function api(page:Page,method:string,url:string,body?:unknown,csrf?:string){return page.evaluate(async({method,url,body,csrf})=>{const response=await fetch(url,{method,headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,data:await response.json().catch(()=>null)};},{method,url,body,csrf});}
const stored=async(id:string)=>(await pool.query('SELECT * FROM brands WHERE id=$1',[id])).rows[0];
const gallery=async(id:string)=>(await pool.query('SELECT media_reference FROM brand_media WHERE brand_id=$1 ORDER BY sort_order',[id])).rows.map(r=>r.media_reference);
async function tab(page:Page,key:string){await page.locator('[data-tab='+key+']').click();await expect(page.locator('[data-pane='+key+']')).toBeVisible();}
async function open(page:Page,id:string){await page.locator('[data-brand-id="'+id+'"] .brand-actions > button').click();await page.locator('[data-brand-id="'+id+'"] [data-brand-action=edit]').click();await expect(page.locator('#brand-dialog')).toBeVisible();await expect(page.locator('#brand-dialog')).toHaveAttribute('data-entity-id',id);}
async function expand(page:Page){if(await page.locator('[data-translatable-field="brand-name"] [data-translation-toggle]').getAttribute('aria-expanded')==='false')await page.locator('[data-translatable-field="brand-name"] [data-translation-toggle]').click();}
async function save(page:Page,key:string){const endpoint=key==='translations'?'/translations':key==='gallery'?'/gallery':'';const response=page.waitForResponse(r=>r.url().includes('/cpanel/api/brands')&&r.request().method()!=='GET'&&(!endpoint||r.url().endsWith(endpoint)));await page.locator(key==='translations'?'[data-translatable-field="brand-name"] [data-save-field]':'[data-save='+key+']').click();expect((await response).ok()).toBe(true);await expect(page.locator(key==='translations'?'[data-translatable-field="brand-name"] [data-save-field]':'[data-save='+key+']')).toBeDisabled();}
async function pick(page:Page,files:string[]){await expect(page.locator('[data-media-picker]')).toBeVisible();await page.locator('[data-picker-path="'+folder+'"]').click();for(const file of files)await page.locator('[data-picker-path="'+folder+'/'+file+'"]').click();await page.locator('[data-picker-confirm]').click();await expect(page.locator('[data-media-picker]')).toBeHidden();}
async function action(page:Page,file:string,kind:string){const item=page.locator('[data-media-path="'+folder+'/'+file+'"]');await item.locator('.gallery-menu > button').click();await item.locator('[data-gallery-action='+kind+']').click();}
async function close(page:Page){await page.locator('#brand-dialog .btn-close[data-bs-dismiss]').click();await expect(page.locator('#brand-dialog')).toBeHidden();}
async function reopen(page:Page,id:string){await close(page);await page.reload();await open(page,id);}

test('real Create → Edit, three independent saves, canonical Main/Gallery, persisted reloads, visibility and search',async({page,context,baseURL})=>{
 test.setTimeout(90000);const actor=await login(context,baseURL!),name='Persistent '+randomUUID();try{
 await page.goto('/cpanel/brands');await expect(page.locator('#brands-filter')).toHaveValue('all');await page.locator('#brands-add').click();for(const sel of ['[data-translatable-field="brand-name"] [data-translation-toggle]','#brand-main-select','[data-tab=gallery]'])await expect(page.locator(sel)).toBeDisabled();await page.locator('#brand-name').fill(' ');await page.locator('[data-save=basic]').click();await expect(page.locator('#brand-name-error')).toBeVisible();await page.locator('#brand-name').fill(name);await save(page,'basic');const id=(await page.locator('#brand-dialog').getAttribute('data-entity-id'))!;expect(id).toMatch(/^\d+$/);await expect(page.locator('#brand-dialog')).toHaveAttribute('data-mode','edit');await expect(page.locator('#brand-dialog')).toBeVisible();expect((await stored(id)).is_visible).toBe(false);expect((await stored(id)).main_media_reference).toBeNull();expect(await gallery(id)).toEqual([]);await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-count]')).toHaveText('0 / 3');
 await page.locator('#brand-name').fill(name+' New');await expand(page);await page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]').fill('Пример');await page.locator('#brand-main-select').click();await pick(page,['a.png']);await tab(page,'gallery');await page.locator('#content-add-media').click();await pick(page,['a.png','b.png','c.png']);
 await tab(page,'basic');await save(page,'translations');expect((await stored(id)).name).toBe(name);expect((await stored(id)).main_media_reference).toBeNull();expect(await gallery(id)).toEqual([]);await expect(page.locator('[data-tab-state=basic]')).toHaveText('Unsaved');await expect(page.locator('[data-tab-state=gallery]')).toHaveText('Unsaved');
 await tab(page,'gallery');await save(page,'gallery');expect(await gallery(id)).toEqual(['a.png','b.png','c.png'].map(f=>folder+'/'+f));expect((await stored(id)).name).toBe(name);await tab(page,'basic');await save(page,'basic');expect((await stored(id)).main_media_reference).toBe(folder+'/a.png');await reopen(page,id);await expect(page.locator('#brand-name')).toHaveValue(name+' New');await expand(page);await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]')).toHaveValue('Пример');await expect(page.locator('#brand-main-preview img')).toHaveAttribute('src','/media/'+folder+'/a.png');
 await page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]').fill(' ');await save(page,'translations');expect((await pool.query('SELECT 1 FROM brand_translations WHERE brand_id=$1',[id])).rowCount).toBe(0);await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-row=ru] [data-translation-fallback]')).toContainText(name+' New');
 await tab(page,'gallery');await page.locator('#content-add-media').click();await page.locator('[data-picker-path="'+folder+'"]').click();await expect(page.locator('[data-picker-path="'+folder+'/a.png"]')).toBeDisabled();await page.locator('[data-picker-cancel]').last().click();await action(page,'b.png','later');await save(page,'gallery');await reopen(page,id);await tab(page,'gallery');expect(await gallery(id)).toEqual(['a.png','c.png','b.png'].map(f=>folder+'/'+f));await action(page,'c.png','remove');await save(page,'gallery');await action(page,'a.png','remove');await save(page,'gallery');await tab(page,'basic');await expect(page.locator('#brand-main-preview img')).toHaveAttribute('src','/media/'+folder+'/a.png');await page.locator('#brand-main-select').click();await pick(page,['b.png']);await save(page,'basic');await page.locator('#brand-main-remove').click();await save(page,'basic');expect(await gallery(id)).toEqual([folder+'/b.png']);await page.locator('#brand-visibility').selectOption('visible');await save(page,'basic');await reopen(page,id);await expect(page.locator('#brand-visibility')).toHaveValue('visible');await expect(page.locator('#brand-main-preview img')).toHaveCount(0);await tab(page,'gallery');await expect(page.locator('#content-gallery .content-media')).toHaveCount(1);await close(page);
 await page.locator('#brands-search').fill(name.toLowerCase());await expect(page.locator('.brand-item')).toHaveCount(1);await page.locator('#brands-filter').selectOption('hidden');await expect(page.locator('.brand-item')).toHaveCount(0);await page.locator('#brands-filter').selectOption('visible');await expect(page.locator('.brand-item')).toHaveCount(1);for(const view of ['list','grid']){await page.locator('button[data-view='+view+']').click();await expect(page.locator('#brands-search')).toHaveValue(name.toLowerCase());await expect(page.locator('#brands-filter')).toHaveValue('visible');await expect(page.locator('[data-brand-id="'+id+'"] .brand-image img')).toHaveCount(0);}for(const f of ['a.png','b.png','c.png'])expect(await readFile(path.join(root,f))).toEqual(pixel);
 }finally{await cleanup(page,actor.id);}
});

test('API CSRF, independent permissions, malicious fields, visibility escalation and current Media permissions',async({page,context,baseURL})=>{
 const actor=await login(context,baseURL!);try{
 await page.goto('/cpanel/brands');const created=await api(page,'POST','/cpanel/api/brands',{name:'Security '+randomUUID()},actor.csrf);expect(created.status).toBe(201);const id=created.data.row.id;
 const mutations:[string,string,unknown][]=[['POST','/cpanel/api/brands',{name:'Denied create'}],['PATCH','/cpanel/api/brands/'+id,{name:'Denied'}],['PATCH','/cpanel/api/brands/'+id,{is_visible:true}],['PUT','/cpanel/api/brands/'+id+'/translations',{translations:{ru:'Denied'}}],['PUT','/cpanel/api/brands/'+id+'/gallery',{original:[],items:[folder+'/a.png']}]];
 for(const [method,url,body] of mutations)for(const csrf of [undefined,'bad'])expect((await api(page,method,url,body,csrf)).status).toBe(403);expect((await stored(id)).is_visible).toBe(false);expect(await gallery(id)).toEqual([]);
 for(const key of ['id','created_by','updated_by','created_at','updated_at','translation_count','gallery_count','effective_name'])expect((await api(page,'PATCH','/cpanel/api/brands/'+id,{[key]:'forged'},actor.csrf)).status).toBe(400);
 await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'brands.view','true'),($1,'brands.update','true')",[actor.id]);await page.reload();await expect(page.locator('#brands-add')).toHaveCount(0);await open(page,id);await expect(page.locator('#brand-main-select')).toBeDisabled();await expect(page.locator('#brand-visibility')).toBeDisabled();expect((await api(page,'PATCH','/cpanel/api/brands/'+id,{is_visible:true},actor.csrf)).status).toBe(403);expect((await api(page,'PATCH','/cpanel/api/brands/'+id,{main_media_reference:folder+'/a.png'},actor.csrf)).status).toBe(403);
 expect((await api(page,'PATCH','/cpanel/api/brands/'+id,{name:'Allowed'},actor.csrf)).status).toBe(200);expect((await api(page,'PUT','/cpanel/api/brands/'+id+'/translations',{translations:{ru:'Allowed'}},actor.csrf)).status).toBe(200);
 await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'media.view','true')",[actor.id]);await page.reload();await open(page,id);await page.locator('#brand-main-select').click();await expect(page.locator('[data-picker-upload]')).toHaveCount(0);await pick(page,['a.png']);await save(page,'basic');
 await pool.query("DELETE FROM cpanel_user_permissions WHERE user_id=$1 AND key='brands.update'",[actor.id]);for(const [method,url,body] of mutations.slice(1))expect((await api(page,method,url,body,actor.csrf)).status).toBe(403);await pool.query("DELETE FROM cpanel_user_permissions WHERE user_id=$1 AND key='brands.view'",[actor.id]);expect((await page.goto('/cpanel/brands'))?.status()).toBe(403);expect((await api(page,'GET','/cpanel/api/brands/'+id)).status).toBe(403);expect((await stored(id)).is_visible).toBe(false);
 }finally{await cleanup(page,actor.id);}
});

test('real independent save failures retain drafts; stale Gallery save conflicts safely',async({page,context,baseURL})=>{
 const actor=await login(context,baseURL!);try{await page.goto('/cpanel/brands');await page.locator('#brands-add').click();await page.locator('#brand-name').fill('Failure '+randomUUID());
 await page.route('**/cpanel/api/brands',async route=>route.request().method()==='POST'?route.fulfill({status:500,json:{success:false,code:'BRAND_SAVE_FAILED'}}):route.continue());await page.locator('[data-save=basic]').click();await expect(page.locator('#brand-status')).toContainText('Save failed');await expect(page.locator('#brand-dialog')).toHaveAttribute('data-mode','create');await expect(page.locator('#brand-main-select')).toBeDisabled();await page.unroute('**/cpanel/api/brands');await save(page,'basic');const id=(await page.locator('#brand-dialog').getAttribute('data-entity-id'))!;
 await expand(page);await page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]').fill('Pending');await page.route('**/cpanel/api/brands/'+id+'/translations',route=>route.fulfill({status:500,json:{success:false,code:'BRAND_SAVE_FAILED'}}));await page.locator('[data-translatable-field="brand-name"] [data-save-field]').click();await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-status]')).toContainText('Save failed');await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]')).toHaveValue('Pending');expect((await pool.query('SELECT 1 FROM brand_translations WHERE brand_id=$1',[id])).rowCount).toBe(0);await page.unroute('**/cpanel/api/brands/'+id+'/translations');await save(page,'translations');
 await page.locator('#brand-name').fill('Unsaved Basic');await page.route('**/cpanel/api/brands/'+id,route=>route.request().method()==='PATCH'?route.fulfill({status:500,json:{success:false,code:'BRAND_SAVE_FAILED'}}):route.continue());await page.locator('[data-save=basic]').click();await expect(page.locator('[data-tab-state=basic]')).toContainText('Save failed');await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-status]')).toHaveText('Changes saved.');await page.unroute('**/cpanel/api/brands/'+id);
 await tab(page,'gallery');await page.locator('#content-add-media').click();await pick(page,['a.png']);expect((await api(page,'PUT','/cpanel/api/brands/'+id+'/gallery',{original:[],items:[folder+'/b.png']},actor.csrf)).status).toBe(200);await page.locator('[data-save=gallery]').click();await expect(page.locator('#brand-status')).toContainText('gallery changed elsewhere');await expect(page.locator('[data-tab-state=gallery]')).toContainText('Save failed');expect(await gallery(id)).toEqual([folder+'/b.png']);await expect(page.locator('[data-media-path="'+folder+'/a.png"]')).toBeVisible();
 await page.locator('#brand-dialog .btn-close[data-bs-dismiss]').click();await expect(page.locator('#brand-discard')).toBeVisible();await page.locator('#brand-keep').click();await tab(page,'basic');await expect(page.locator('#brand-name')).toHaveValue('Unsaved Basic');await page.locator('#brand-dialog .btn-close[data-bs-dismiss]').click();await page.locator('#brand-discard-confirm').click();await expect(page.locator('#brand-dialog')).toBeHidden();await open(page,id);expect(await page.locator('#brand-name').inputValue()).not.toBe('Unsaved Basic');await expand(page);await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]')).toHaveValue('Pending');
 }finally{await cleanup(page,actor.id);}
});

test('Picker real upload, folder/search, image eligibility, missing files and preserved DB links',async({page,context,baseURL})=>{
 const actor=await login(context,baseURL!);let choosers=0;page.on('filechooser',()=>choosers++);try{
 await page.goto('/cpanel/brands');const id=(await api(page,'POST','/cpanel/api/brands',{name:'Media '+randomUUID()},actor.csrf)).data.row.id;await page.reload();await open(page,id);await page.locator('#brand-main-select').click();expect(choosers).toBe(0);await page.locator('[data-picker-path="'+folder+'"]').click();await expect(page.locator('[data-picker-path="'+folder+'/text.txt"]')).toBeDisabled();await page.locator('[data-picker-search]').fill('a.png');await expect(page.locator('[data-picker-path="'+folder+'/a.png"]')).toBeVisible();await page.locator('[data-picker-view=list]').click();await expect(page.locator('[data-picker-search]')).toHaveValue('a.png');await page.locator('[data-picker-search]').fill('');
 const chooser=page.waitForEvent('filechooser');await page.locator('[data-picker-upload]').click();await (await chooser).setFiles({name:'brand-upload.png',mimeType:'image/png',buffer:pixel});await expect(page.locator('[data-picker-path="'+folder+'/brand-upload.png"]')).toBeVisible();expect(choosers).toBe(1);await expect(page.locator('[data-picker-confirm]')).toBeDisabled();expect((await stored(id)).main_media_reference).toBeNull();await page.locator('[data-picker-path="'+folder+'/brand-upload.png"]').click();await page.locator('[data-picker-confirm]').click();await save(page,'basic');expect((await stored(id)).main_media_reference).toBe(folder+'/brand-upload.png');expect(await readFile(path.join(root,'brand-upload.png'))).toEqual(pixel);
 await tab(page,'gallery');await page.locator('#content-add-media').click();await pick(page,['brand-upload.png','a.png']);await save(page,'gallery');await close(page);
 // Use the existing File Manager's real delete operation only on this test artifact.
 expect((await api(page,'POST','/cpanel/api/media/delete',{path:folder+'/brand-upload.png',recursive:false},actor.csrf)).status).toBe(200);await page.reload();await expect(page.locator('[data-brand-id="'+id+'"] .brand-image img')).toHaveCount(0);await open(page,id);await expect(page.locator('#brand-main-preview img')).toHaveCount(0);await expect(page.locator('#brand-main-identity')).toContainText('brand-upload.png');await tab(page,'gallery');await expect(page.locator('#content-gallery .content-media')).toHaveCount(2);await expect(page.locator('[data-media-path="'+folder+'/brand-upload.png"] img')).toHaveCount(0);expect((await stored(id)).main_media_reference).toBe(folder+'/brand-upload.png');expect(await gallery(id)).toEqual([folder+'/brand-upload.png',folder+'/a.png']);await action(page,'brand-upload.png','remove');await save(page,'gallery');expect((await stored(id)).main_media_reference).toBe(folder+'/brand-upload.png');
 }finally{await cleanup(page,actor.id);}
});

test('dynamic registry language + tm/ru/en production workflow, themes and responsive screens',async({page,context,baseURL})=>{
 test.setTimeout(120000);const actor=await login(context,baseURL!),extra='brand-'+randomUUID().slice(0,8);try{
 await pool.query('INSERT INTO languages(code,display_name) VALUES($1,$2)',[extra,'Extra language']);await page.goto('/cpanel/brands');const id=(await api(page,'POST','/cpanel/api/brands',{name:'Languages '+randomUUID()},actor.csrf)).data.row.id;await page.reload();await open(page,id);await expand(page);await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-input]')).toHaveCount(4);await page.locator('[data-translatable-field="brand-name"] [data-translation-input="'+extra+'"]').fill('Additional override');await save(page,'translations');expect((await pool.query('SELECT name FROM brand_translations WHERE brand_id=$1 AND language_code=$2',[id,extra])).rows[0].name).toBe('Additional override');await close(page);await pool.query('UPDATE languages SET is_active=false WHERE code=$1',[extra]);
 const values=(await pool.query('SELECT * FROM interface_translations')).rows;await page.emulateMedia({reducedMotion:'reduce'});
 for(const [language,width] of [['tm',1440],['ru',768],['en',375]] as const){const t=(key:string)=>values.find(v=>v.language_code===language&&v.translation_key===key).translation_value;await page.locator('#shell-language').selectOption(language);await expect(page.locator('html')).toHaveAttribute('lang',language);await expect(page.locator('h1')).toHaveText(t('cpanel.navigation.brands'));await open(page,id);await expand(page);await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-input]')).toHaveCount(3);await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-row=tm] [data-translation-fallback]')).toContainText(t('cpanel.content.usesDefault'));await page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]').fill('Язык '+language);await save(page,'translations');await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-status]')).toHaveText(t('cpanel.brands.persistedSaved'));await close(page);
 for(const theme of ['light','dark']){await page.setViewportSize({width,height:1000});await page.evaluate(theme=>document.documentElement.dataset.bsTheme=theme,theme);await open(page,id);await expand(page);expect(await page.locator('body').innerText()).not.toMatch(/cpanel\.(brands|content|media)\./);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);await page.screenshot({path:`artifacts/brands-active-${language}-${theme}-${width}-basic.png`});await page.locator('[data-translatable-field="brand-name"] [data-translation-toggle]').click();await page.locator('#brand-main-select').click();await expect(page.locator('[data-picker-permanent-only]')).toHaveText(t('cpanel.media.pickerPermanentOnly'));await page.locator('[data-picker-path="'+folder+'"]').click();await page.screenshot({path:`artifacts/brands-active-${language}-${theme}-${width}-picker.png`});await page.locator('[data-picker-cancel]').last().click();await tab(page,'gallery');if(await page.locator('#content-gallery .content-media').count()===0){await page.locator('#content-add-media').click();await pick(page,['a.png','b.png']);await save(page,'gallery');}await page.locator('[data-media-path="'+folder+'/a.png"] .gallery-menu > button').click();await page.screenshot({path:`artifacts/brands-active-${language}-${theme}-${width}-gallery.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);await page.keyboard.press('Escape');await close(page);}
 }
 }finally{await cleanup(page,actor.id);await pool.query('DELETE FROM languages WHERE code=$1',[extra]);}
});

test('compiled application restart retains Brand, translations, Main Image, visibility and Gallery order',async({page,context,baseURL})=>{
 test.setTimeout(60000);const actor=await login(context,baseURL!);let child:ChildProcess|undefined;
 const listener=createServer();listener.listen(0,'127.0.0.1');await once(listener,'listening');const port=(listener.address() as {port:number}).port;await new Promise<void>(resolve=>listener.close(()=>resolve()));
 const stop=async()=>{if(child&&child.exitCode===null){const ended=once(child,'exit');child.kill('SIGTERM');await ended;}child=undefined;};
 try{
  await page.goto('/cpanel/brands');const name='Restart '+randomUUID(),id=(await api(page,'POST','/cpanel/api/brands',{name},actor.csrf)).data.row.id;
  expect((await api(page,'PATCH','/cpanel/api/brands/'+id,{main_media_reference:folder+'/a.png',is_visible:true},actor.csrf)).status).toBe(200);
  expect((await api(page,'PUT','/cpanel/api/brands/'+id+'/translations',{translations:{tm:'At',ru:'Имя',en:'Name'}},actor.csrf)).status).toBe(200);
  expect((await api(page,'PUT','/cpanel/api/brands/'+id+'/gallery',{original:[],items:[folder+'/c.png',folder+'/b.png']},actor.csrf)).status).toBe(200);
  for(let restart=0;restart<2;restart++){
   child=spawn(process.execPath,['--enable-source-maps','dist/server.js'],{env:{...process.env,NODE_ENV:'production',HOST:'127.0.0.1',PORT:String(port),VENDOR_SYNC_ENABLED:'false',MEDIA_ROOT:path.resolve('.test-media')},stdio:'ignore'});
   await expect.poll(async()=>{try{return (await fetch('http://127.0.0.1:'+port+'/health',{signal:AbortSignal.timeout(500)})).status;}catch{return 0;}},{timeout:15000}).toBe(200);
   await page.goto('http://127.0.0.1:'+port+'/cpanel/brands');const result=await api(page,'GET','/cpanel/api/brands/'+id);expect(result.status).toBe(200);expect(result.data.row.basic).toMatchObject({name,is_visible:true,mainMedia:{path:folder+'/a.png'}});expect(result.data.row.translations).toEqual({tm:'At',ru:'Имя',en:'Name'});expect(result.data.row.gallery.map((item:any)=>item.path)).toEqual([folder+'/c.png',folder+'/b.png']);await stop();
  }
 }finally{await stop();await cleanup(page,actor.id);}
});

test('activated Brands navigation follows fresh view permissions without enabling Source Products',async({page,context,baseURL})=>{
 const actor=await login(context,baseURL!);try{
 await page.goto('/cpanel');await expect(page.locator('[data-navigation-id=brands]')).toHaveAttribute('data-availability','enabled');await page.locator('[data-navigation-id=brands] a').click();await expect(page).toHaveURL(/\/cpanel\/brands$/);await expect(page.locator('[data-navigation-id=brands]')).toHaveClass(/is-active/);await expect(page.locator('[data-navigation-id=sourceProducts]')).toHaveAttribute('data-availability','disabled');
 await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);for(const value of [false,'true',true]){await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'brands.view',$2) ON CONFLICT(user_id,key) DO UPDATE SET value=excluded.value",[actor.id,JSON.stringify(value)]);await page.goto('/cpanel');await expect(page.locator('[data-navigation-id=brands]')).toHaveCount(value===true?1:0);expect((await page.goto('/cpanel/brands'))?.status()).toBe(value===true?200:403);}
 }finally{await cleanup(page,actor.id);}
});

test('retained Picker regressions: cancellation focus, stale search, confirmation revalidation, revocation and universal upload',async({page,context,baseURL})=>{
 test.setTimeout(60000);const actor=await login(context,baseURL!);try{
 await page.goto('/cpanel/brands');const id=(await api(page,'POST','/cpanel/api/brands',{name:'Picker safety '+randomUUID()},actor.csrf)).data.row.id;await page.reload();await open(page,id);
 await expect(page.locator('[data-tab]')).toHaveCount(4);await expect(page.locator('[data-tab=translations],#content-language,[data-gallery-action=primary],[data-brand-action=delete]')).toHaveCount(0);
 const toggle=page.locator('[data-translatable-field="brand-name"] [data-translation-toggle]');await toggle.focus();await page.keyboard.press('Enter');await expect(toggle).toHaveAttribute('aria-expanded','true');await page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]').fill('Draft');await toggle.focus();await page.keyboard.press('Space');await expect(toggle).toHaveAttribute('aria-expanded','false');await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-dirty]')).toBeVisible();await toggle.click();await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]')).toHaveValue('Draft');await save(page,'translations');
 await page.locator('#brand-main-select').click();await page.keyboard.press('Escape');await expect(page.locator('[data-media-picker]')).toBeHidden();await expect(page.locator('#brand-main-select')).toBeFocused();await page.locator('#brand-main-select').click();await page.locator('[data-picker-path="'+folder+'"]').click();await page.locator('[data-picker-scope]').selectOption('current');
 await page.route('**/cpanel/media?**',async route=>{if(new URL(route.request().url()).searchParams.get('query')==='a.png')await new Promise(resolve=>setTimeout(resolve,900));await route.continue().catch(()=>{});});await page.locator('[data-picker-search]').fill('a.png');await page.waitForTimeout(350);await page.locator('[data-picker-search]').fill('c.png');await expect(page.locator('[data-picker-path="'+folder+'/c.png"]')).toBeVisible();await page.waitForTimeout(1000);await expect(page.locator('[data-picker-items] > button')).toHaveCount(1);await page.unroute('**/cpanel/media?**');
 await page.locator('[data-picker-path="'+folder+'/c.png"]').click();await page.route('**/cpanel/api/media/details?**',async route=>{const response=await route.fetch();const data=await response.json();data.item.image=false;data.item.type='file';await route.fulfill({response,json:data});});await page.locator('[data-picker-confirm]').click();await expect(page.locator('[data-picker-notice]')).toHaveText(await page.locator('[data-picker-label=failed]').textContent()??'');await expect(page.locator('[data-media-picker]')).toBeVisible();await page.unroute('**/cpanel/api/media/details?**');
 await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);await page.locator('[data-picker-confirm]').click();await expect(page.locator('[data-picker-notice]')).toContainText('Access denied');expect((await stored(id)).main_media_reference).toBeNull();await page.locator('[data-picker-cancel]').last().click();
 await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'superuser','true')",[actor.id]);await page.locator('#brand-main-select').click();await page.locator('[data-picker-path="'+folder+'"]').click();await page.locator('[data-media-picker]').evaluate(el=>el.setAttribute('data-csrf','invalid'));await page.locator('[data-picker-files]').setInputFiles({name:'denied-upload.txt',mimeType:'text/plain',buffer:Buffer.from('denied')});await expect(page.locator('[data-picker-upload-status]')).toContainText('Access denied');await expect(page.locator('[data-picker-path="'+folder+'/denied-upload.txt"]')).toHaveCount(0);
 await page.locator('[data-media-picker]').evaluate((el,csrf)=>el.setAttribute('data-csrf',csrf),actor.csrf);await page.locator('[data-picker-files]').setInputFiles({name:'universal-note.txt',mimeType:'text/plain',buffer:Buffer.from('Universal upload')});await expect(page.locator('[data-picker-path="'+folder+'/universal-note.txt"]')).toBeDisabled();expect(await readFile(path.join(root,'universal-note.txt'),'utf8')).toBe('Universal upload');await page.locator('[data-picker-cancel]').last().click();expect((await stored(id)).main_media_reference).toBeNull();
 }finally{await cleanup(page,actor.id);}
});

test('registry-driven Brands management and independent read/create/update/visibility UI capabilities',async({page,context,baseURL})=>{
 const actor=await login(context,baseURL!),target=(await bootstrapSuperuser({name:'Registry verification',email:randomUUID()+'@example.invalid',password:randomUUID()})).id;try{await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[target]);
 await page.goto('/cpanel');await page.goto('/cpanel/permissions/'+target);for(const key of ['view','create','update','visibility'])await expect(page.locator('[data-permission-key="brands.'+key+'"]')).toBeVisible();await expect(page.locator('[data-permission-key="brands.delete"]')).toHaveCount(0);
 const id=(await api(page,'POST','/cpanel/api/brands',{name:'Capabilities '+randomUUID()},actor.csrf)).data.row.id;
 for(const right of ['', 'create','update','visibility']){await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'brands.view','true')",[actor.id]);if(right)await pool.query('INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,$2,$3)',[actor.id,'brands.'+right,'true']);await page.goto('/cpanel/brands');await expect(page.locator('#brands-add')).toHaveCount(right==='create'?1:0);await open(page,id);await expect(page.locator('#brand-name')).toBeEnabled({enabled:right==='update'});await expect(page.locator('#brand-visibility')).toBeEnabled({enabled:right==='visibility'});await expand(page);await expect(page.locator('[data-translatable-field="brand-name"] [data-translation-input=ru]')).toBeEnabled({enabled:right==='update'});await expect(page.locator('[data-save=basic]')).toBeDisabled();await close(page);}
 }finally{await cleanup(page,actor.id);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[target]);}
});
