import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
test.use({actionTimeout:10000});
const folder='categories-ui-'+randomUUID(),root=path.resolve('.test-media',folder);
test.beforeAll(async()=>{await mkdir(root,{recursive:true});for(const file of ['a.png','b.png'])await writeFile(path.join(root,file),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8x8AAAAASUVORK5CYII=','base64'));});
test.afterAll(async()=>{await rm(root,{recursive:true,force:true});});
async function login(context:any,baseURL:string,live=false){const user=await bootstrapSuperuser({name:'Categories UI test',email:randomUUID()+'@example.invalid',password:randomUUID()});const session=await sessions.create(user.id);await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'&&!live?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1'&&!live,httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL}]);return user.id;}
const dialog=(page:Page)=>page.locator('#brand-dialog');
async function save(page:Page,key:string){const pending=page.waitForResponse(r=>r.url().includes('/cpanel/api/categories')&&r.request().method()!=='GET');await page.locator('[data-save='+key+']').click();expect((await pending).ok()).toBe(true);await expect(page.locator('[data-save='+key+']')).toBeDisabled();}
async function tab(page:Page,key:string){await page.locator('[data-tab='+key+']').click();await expect(page.locator('[data-pane='+key+']')).toBeVisible();}
async function open(page:Page,id:string){await page.locator('[data-category-id="'+id+'"] .category-open').click();}
async function edit(page:Page,id:string){const item=page.locator('[data-category-id="'+id+'"]');await item.locator('.brand-actions > button').click();await item.locator('[data-category-action=edit]').click();await expect(dialog(page)).toBeVisible();}
async function close(page:Page){await page.waitForFunction(()=>{const modal=(window as any).bootstrap.Modal.getInstance(document.getElementById('brand-dialog'));return modal?._isShown&&!modal._isTransitioning;});await dialog(page).locator('.btn-close[data-bs-dismiss]').click();await expect(dialog(page)).toBeHidden();}
async function pick(page:Page,files:string[]){await expect(page.locator('[data-media-picker]')).toBeVisible();await page.locator('[data-picker-path="'+folder+'"]').click();for(const file of files)await page.locator('[data-picker-path="'+folder+'/'+file+'"]').click();await page.locator('[data-picker-confirm]').click();await expect(page.locator('[data-media-picker]')).toBeHidden();}

async function api(page:Page,method:string,url:string,body?:unknown,csrf?:string){return page.evaluate(async({method,url,body,csrf})=>{const response=await fetch(url,{method,headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,data:await response.json().catch(()=>null)};},{method,url,body,csrf});}
const stored=async(id:string)=>(await pool.query('SELECT * FROM categories WHERE id=$1',[id])).rows[0];
async function cleanup(page:Page,id:string){await page.goto('about:blank').catch(()=>{});await pool.query('DELETE FROM category_media WHERE category_id IN(SELECT id FROM categories WHERE created_by=$1)',[id]);await pool.query('DELETE FROM category_translations WHERE category_id IN(SELECT id FROM categories WHERE created_by=$1)',[id]);await pool.query('UPDATE categories SET parent_id=NULL WHERE created_by=$1',[id]);await pool.query('DELETE FROM categories WHERE created_by=$1',[id]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[id]);}
async function create(page:Page,csrf:string,name:string,parent_id:string|null=null){const result=await api(page,'POST','/cpanel/api/categories',{name,parent_id},csrf);expect(result.status).toBe(201);return result.data.row.id as string;}

test('persistent Categories hierarchy/browser/Create/Edit/SEO/translations/Main Image/Gallery/reload',async({page,context,baseURL})=>{
 const actor=await login(context,baseURL!),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));try{
 expect((await page.goto('/cpanel/categories'))?.status()).toBe(200);const csrf=(await page.locator('#categories-page').getAttribute('data-csrf'))!,prefix='UI-'+randomUUID().slice(0,8);
 const a=await create(page,csrf,prefix+' A'),b=await create(page,csrf,prefix+' B',a),c=await create(page,csrf,prefix+' C',b),d=await create(page,csrf,prefix+' D',c),x=await create(page,csrf,prefix+' X');
 await page.goto('/cpanel/categories#'+a);await expect(page.locator('[data-category-id="'+b+'"]')).toBeVisible();for(const id of [b,c,d])await open(page,id);await expect(page.locator('#category-breadcrumbs [aria-current]')).toHaveText(prefix+' D');
 await page.locator('[data-category-crumb="'+a+'"]').click();await edit(page,b);await page.locator('#category-parent-toggle').click();await page.locator('#category-parent-search').fill(prefix+' C');await expect(page.locator('[data-parent-choice="'+c+'"]')).toBeDisabled();await page.locator('#category-parent-search').fill(prefix+' X');await page.locator('[data-parent-choice="'+x+'"]:not(:disabled)').click();await save(page,'basic');await close(page);
 await page.locator('#categories-search').fill(prefix+' D');await expect(page.locator('[data-category-id="'+d+'"] [data-path]')).toHaveText(prefix+' X / '+prefix+' B / '+prefix+' C');await open(page,d);await expect(page.locator('#category-breadcrumbs [aria-current]')).toHaveText(prefix+' D');
 await page.goto('/cpanel/categories#'+a);await expect(page.locator('#category-breadcrumbs [aria-current]')).toHaveText(prefix+' A');await page.locator('#categories-add').click();await expect(page.locator('#category-parent-toggle')).toHaveText(prefix+' A');for(const key of ['seo','gallery','products'])await expect(page.locator('[data-tab='+key+']')).toBeDisabled();await page.locator('#brand-name').fill(prefix+' Created');await save(page,'basic');const id=(await dialog(page).getAttribute('data-entity-id'))!;expect(id).toMatch(/^\d+$/);await expect(dialog(page)).toBeVisible();expect((await stored(id)).parent_id).toBe(a);expect((await stored(id)).is_visible).toBe(false);
 const name=page.locator('[data-translatable-field=brand-name]');await name.locator('[data-translation-toggle]').click();await name.locator('[data-translation-input=ru]').fill('Категория');await name.locator('[data-save-field]').click();await expect(name.locator('[data-save-field]')).toBeDisabled();
 await page.locator('#brand-name').fill(prefix+' Pending');await tab(page,'seo');await page.locator('#brand-slug').fill('category-'+id);await page.locator('#brand-seo_title').fill('SEO title');await page.locator('#brand-seo_description').fill('SEO description');await save(page,'seo');expect((await stored(id)).name).toBe(prefix+' Created');await expect(page.locator('[data-tab-state=basic]')).toHaveText('Unsaved');
 const title=page.locator('[data-translatable-field=brand-seo_title]');await title.locator('[data-translation-toggle]').click();await title.locator('[data-translation-input=tm]').fill('SEO synagy');await title.locator('[data-save-field]').click();await expect(title.locator('[data-save-field]')).toBeDisabled();
 await tab(page,'basic');await page.locator('#brand-main-select').click();await pick(page,['a.png']);await page.locator('#brand-visibility').selectOption('visible');await save(page,'basic');expect((await stored(id)).seo_title).toBe('SEO title');
 await tab(page,'gallery');await page.locator('#content-add-media').click();await pick(page,['a.png','b.png']);await save(page,'gallery');const first=page.locator('[data-media-path="'+folder+'/a.png"]');await first.locator('.gallery-menu > button').click();await first.locator('[data-gallery-action=later]').click();await save(page,'gallery');await expect(page.locator('#content-gallery [data-media-path]').first()).toHaveAttribute('data-media-path',folder+'/b.png');await first.locator('.gallery-menu > button').click();await first.locator('[data-gallery-action=remove]').click();await save(page,'gallery');
 await tab(page,'products');await expect(page.locator('#brand-product-count')).toHaveText('Direct products: 0 · Including subcategories: 0');await close(page);await page.reload();await edit(page,id);await expect(page.locator('#brand-name')).toHaveValue(prefix+' Pending');await expect(page.locator('#brand-main-preview img')).toBeVisible();await expect(page.locator('#brand-visibility')).toHaveValue('visible');await tab(page,'seo');await expect(page.locator('#brand-slug')).toHaveValue('category-'+id);await expect(page.locator('#brand-seo_title')).toHaveValue('SEO title');await title.locator('[data-translation-toggle]').click();await expect(title.locator('[data-translation-input=tm]')).toHaveValue('SEO synagy');await tab(page,'gallery');await expect(page.locator('#content-gallery [data-media-path]')).toHaveCount(1);await close(page);
 await page.locator('[data-view=list]').click();await expect(page.locator('#categories-page')).toHaveAttribute('data-view','list');await page.locator('#categories-filter').selectOption('hidden');await expect(page.locator('[data-category-id="'+id+'"]')).toHaveCount(0);await page.locator('#categories-filter').selectOption('visible');await expect(page.locator('[data-category-id="'+id+'"]')).toBeVisible();
 expect(errors).toEqual([]);
 }finally{await cleanup(page,actor);}
});

test('Categories HTTP CSRF and independent permissions remain authoritative',async({page,context,baseURL})=>{
 const actor=await login(context,baseURL!);try{
 await page.goto('/cpanel/categories');const csrf=(await page.locator('#categories-page').getAttribute('data-csrf'))!,id=await create(page,csrf,'HTTP '+randomUUID());
 for(const [method,url,body]of [['POST','/cpanel/api/categories',{name:'No CSRF'}],['PATCH','/cpanel/api/categories/'+id,{name:'No CSRF'}],['PATCH','/cpanel/api/categories/'+id+'/seo',{seo_title:'No CSRF'}],['PUT','/cpanel/api/categories/'+id+'/translations',{translations:{en:'No CSRF'}}],['PUT','/cpanel/api/categories/'+id+'/gallery',{original:[],items:[]}]] as const)expect((await api(page,method,url,body)).status).toBe(403);
 expect((await api(page,'PATCH','/cpanel/api/categories/'+id,{parent_id:id},csrf)).status).toBe(400);
 await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor]);await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'categories.view','true')",[actor]);await page.reload();await edit(page,id);await expect(page.locator('#brand-name')).toBeDisabled();await expect(page.locator('[data-save=basic]')).toBeDisabled();expect((await api(page,'PATCH','/cpanel/api/categories/'+id,{name:'Denied'},csrf)).status).toBe(403);await close(page);
 await pool.query("DELETE FROM cpanel_user_permissions WHERE user_id=$1",[actor]);await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'categories.update','true')",[actor]);expect((await api(page,'GET','/cpanel/api/categories')).status).toBe(403);expect((await api(page,'PATCH','/cpanel/api/categories/'+id,{name:'Updated'},csrf)).status).toBe(200);expect((await api(page,'PATCH','/cpanel/api/categories/'+id,{is_visible:true},csrf)).status).toBe(403);expect((await stored(id)).is_visible).toBe(false);
 }finally{await cleanup(page,actor);}
});

test('Categories actual tm/ru/en activation labels and navigation',async({page,context,baseURL})=>{
 const base=process.env.CATEGORIES_VERIFY_URL??baseURL!,actor=await login(context,base,Boolean(process.env.CATEGORIES_VERIFY_URL));try{
 for(const language of ['tm','ru','en']){await context.addCookies([{name:'hormat_lang',value:language,url:base}]);await page.goto(base+'/cpanel/categories');await expect(page.locator('.shell-sidebar a[href="/cpanel/categories"]')).toBeVisible();await page.locator('#categories-add').click();const corpus=await page.locator('body').evaluate(body=>[body.textContent,...Array.from(body.querySelectorAll('*')).flatMap(el=>['placeholder','aria-label','title'].map(key=>el.getAttribute(key)??''))].join('\n'));for(const row of (await pool.query("SELECT translation_value FROM interface_translations WHERE language_code=$1 AND translation_key IN('cpanel.categories.subtitle','cpanel.categories.created','cpanel.categories.galleryConflict')",[language])).rows)expect(corpus).toContain(row.translation_value);expect(corpus).not.toContain('cpanel.categories.');await close(page);}
 await pool.query("DELETE FROM cpanel_user_permissions WHERE user_id=$1",[actor]);await page.goto(base+'/cpanel');await expect(page.locator('a[href="/cpanel/categories"]')).toHaveCount(0);expect((await page.goto(base+'/cpanel/categories'))?.status()).toBe(403);
 await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'categories.view','true')",[actor]);await page.goto(base+'/cpanel/categories');await expect(page.locator('.shell-sidebar a[href="/cpanel/categories"]')).toBeVisible();
 }finally{await cleanup(page,actor);}
});

test('Category Move action reuses parent picker, confirms path, moves subtree to destination and Root with CSRF protection',async({page,context,baseURL})=>{
 const base=process.env.CATEGORIES_VERIFY_URL??baseURL!,actor=await login(context,base,Boolean(process.env.CATEGORIES_VERIFY_URL));try{
 await page.goto(base+'/cpanel/categories');const csrf=(await page.locator('#categories-page').getAttribute('data-csrf'))!,prefix='Move-'+randomUUID().slice(0,8),a=await create(page,csrf,prefix+' A'),b=await create(page,csrf,prefix+' B',a),c=await create(page,csrf,prefix+' C',b),x=await create(page,csrf,prefix+' X');
 const move=page.locator('#category-move-dialog');
 async function openMove(id:string){const row=page.locator('[data-category-id="'+id+'"]');await row.locator('.brand-actions > button').click();await row.locator('[data-category-action=move]').click();await expect(move).toBeVisible();await page.waitForFunction(()=>{const modal=(window as any).bootstrap.Modal.getInstance(document.getElementById('category-move-dialog'));return modal?._isShown&&!modal._isTransitioning;});}
 for(const language of ['tm','ru','en']){await context.addCookies([{name:'hormat_lang',value:language,url:base}]);await page.goto(base+'/cpanel/categories#'+a);await page.reload();await openMove(b);const values=(await pool.query("SELECT translation_value FROM interface_translations WHERE language_code=$1 AND translation_key IN('cpanel.categories.moveTitle','cpanel.categories.currentLocation','cpanel.categories.newLocation')",[language])).rows;for(const value of values)await expect(move).toContainText(value.translation_value);await move.locator('.btn-close').click();await expect(move).toBeHidden();}
 await openMove(b);await expect(page.locator('#category-move-confirm')).toBeDisabled();await page.locator('#category-parent-search').fill(prefix+' C');await expect(page.locator('[data-parent-choice="'+c+'"]')).toBeDisabled();await page.locator('#category-parent-search').fill(prefix+' X');await page.locator('[data-parent-choice="'+x+'"]:not(:disabled)').click();await expect(page.locator('#category-move-new')).toHaveText(prefix+' X / '+prefix+' B');
 await page.screenshot({path:'artifacts/category-move.png'});const moved=page.waitForResponse(r=>r.url().endsWith('/api/categories/'+b)&&r.request().method()==='PATCH');await page.locator('#category-move-confirm').click();const response=await moved;expect(response.ok()).toBe(true);expect(response.request().postDataJSON()).toEqual({parent_id:x});await expect(move).toBeHidden();await expect(page.locator('[data-category-id="'+b+'"]')).toHaveCount(0);expect((await stored(c)).parent_id).toBe(b);
 await page.goto(base+'/cpanel/categories#'+x);await openMove(b);await page.locator('[data-parent-choice=""]').click();await page.locator('#category-move-confirm').click();await expect(move).toBeHidden();expect((await stored(b)).parent_id).toBe(null);
 expect((await api(page,'PATCH','/cpanel/api/categories/'+b,{parent_id:a})).status).toBe(403);expect((await stored(b)).parent_id).toBe(null);
 await page.goto(base+'/cpanel/categories');await edit(page,a);await page.locator('#category-parent-toggle').click();await expect(page.locator('#brand-dialog #category-parent-picker')).toBeVisible();await close(page);
 await pool.query("DELETE FROM cpanel_user_permissions WHERE user_id=$1",[actor]);await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'categories.view','true')",[actor]);await page.reload();expect((await api(page,'PATCH','/cpanel/api/categories/'+b,{parent_id:a},csrf)).status).toBe(403);await expect(page.locator('[data-category-action=move]')).toHaveCount(0);
 }finally{await cleanup(page,actor);}
});
