import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
import {config} from '../src/config/env.js';
import {VendorCredentials} from '../src/vendors/credentials.js';
async function close(page:Page,id:string){await page.waitForFunction(id=>!(window as any).bootstrap.Modal.getInstance(document.getElementById(id))._isTransitioning,id);await page.locator('#'+id+' .modal-footer [data-bs-dismiss]').click();await expect(page.locator('#'+id)).toBeHidden();await expect(page.locator('.modal-backdrop')).toHaveCount(0);}
async function footer(page:Page,id:string){const buttons=page.locator('#'+id+' .modal-footer button');await expect(buttons).toHaveCount(2);const a=(await buttons.nth(0).boundingBox())!,b=(await buttons.nth(1).boundingBox())!;expect(Math.abs(a.y+a.height/2-b.y-b.height/2)).toBeLessThan(2);expect(b.x).toBeGreaterThan(a.x);}

test('Currency activation: persistent Grid/List, independent translations and rate-only dialogs',async({page,context,baseURL})=>{
 test.setTimeout(90000);const base=process.env.CURRENCIES_VERIFY_URL??baseURL!,live=!!process.env.CURRENCIES_VERIFY_URL,actor=await bootstrapSuperuser({name:'Currencies UI test',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(actor.id);const vendors:string[]=[],prefix='00-CurrencyUI-'+randomUUID();
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'&&!live?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(base).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1'&&!live,httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:base}]);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  for(const suffix of ['A','B'])vendors.push((await pool.query("INSERT INTO vendors(name,url,username,password_encrypted,is_active) VALUES($1,'https://example.invalid/db','fixture',$2,false) RETURNING id",[prefix+suffix,new VendorCredentials(config.vendors.credentialsKey).encryptSecret('fixture')])).rows[0].id);
  const fixtures=(await pool.query("INSERT INTO currencies(vendor_id,source_id,name) VALUES($1,'ui-usd','USD'),($1,'ui-eur','EUR'),($2,'ui-usd','USD'),($2,'ui-main','Main Currency') RETURNING *",vendors)).rows;
  await page.goto(base+'/cpanel/currencies/frontend');await page.locator('#currency-search').fill(prefix);await expect(page.locator('.currency-card')).toHaveCount(0);
  await page.locator('#currency-search').fill('');await page.locator('#currency-filter').selectOption('all');await page.locator('#currency-add').click();await expect(page.locator('[data-translation-toggle]')).toBeDisabled();for(const [field,value]of Object.entries({name:prefix,code:'REV',symbol:'R',rate:'0.125',sort:'15'}))await page.locator('#currency-'+field).fill(value);await page.locator('#currency-save').click();await expect(page.locator('#currency-dialog')).toBeVisible();await expect(page.locator('#currency-dialog')).toHaveAttribute('data-entity-id',/^\d+$/);await expect(page.locator('[data-translation-toggle]')).toBeEnabled();
  await page.locator('[data-translation-toggle]').click();await expect(page.locator('[data-translation-input]')).toHaveCount(3);await page.locator('#currency-name').fill(prefix+' Updated');await page.locator('[data-translation-input=ru]').fill('Валюта');await page.locator('[data-save-field]').click();await expect(page.locator('[data-translation-status]')).toHaveText('Changes saved.');await expect(page.locator('[data-translation-count]')).toHaveText('1 / 3');await expect(page.locator('#currency-save')).toBeEnabled();await page.locator('#currency-save').click();await expect(page.locator('#currency-status')).toHaveText('Changes saved.');await page.locator('[data-translation-input=en]').fill('Uncommitted English');await page.locator('#currency-rate').fill('15.75');await page.locator('#currency-save').click();await expect(page.locator('#currency-status')).toHaveText('Changes saved.');await expect(page.locator('[data-save-field]')).toBeEnabled();await page.locator('[data-translation-input=en]').fill('');await page.locator('[data-save-field]').click();await expect(page.locator('[data-translation-status]')).toHaveText('Changes saved.');await expect(page.locator('[data-save-field]')).toBeDisabled();await footer(page,'currency-dialog');await close(page,'currency-dialog');
  const newCard=page.locator('.currency-card').filter({hasText:prefix+' Updated'});await expect(newCard).toContainText('15.75');await page.locator('button[data-view=list]').click();await expect(newCard).toBeVisible();await newCard.locator('[data-bs-toggle=dropdown]').click();await newCard.locator('[data-action=edit]').click();await page.locator('[data-translation-toggle]').click();await expect(page.locator('[data-translation-input=ru]')).toHaveValue('Валюта');await close(page,'currency-dialog');
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.setAttribute('data-bs-theme',theme),theme);await page.screenshot({path:'artifacts/currencies-list-'+theme+'.png'});}await page.reload();await expect(page.locator('#currencies-page')).toHaveAttribute('data-view','list');await page.locator('#currency-search').fill(prefix);await expect(page.locator('.currency-card')).toHaveCount(1);await expect(page.locator('.currency-card')).toContainText('15.75');await page.locator('.currency-card [data-bs-toggle=dropdown]').click();await page.locator('.currency-card [data-action=visibility]').click();await expect(page.locator('.currency-card [data-visible]')).toHaveText('Visible');await page.locator('#currency-filter').selectOption('hidden');await expect(page.locator('.currency-card')).toHaveCount(0);await page.locator('#currency-filter').selectOption('visible');await expect(page.locator('.currency-card')).toHaveCount(1);await page.locator('button[data-view=grid]').click();await expect(page.locator('#currency-search')).toHaveValue(prefix);await expect(page.locator('#currency-filter')).toHaveValue('visible');
  await page.goto(base+'/cpanel/currencies/vendors');await expect(page.locator('#currency-vendor')).toHaveCount(0);await expect(page.locator('#currency-add')).toHaveCount(0);await expect(page.locator('#currency-rates input')).toHaveCount(0);
  for(const row of fixtures)await expect(page.locator('[data-currency-id="'+row.id+'"]')).toBeVisible();
  await page.locator('#currency-vendor-search').fill(prefix);await expect(page.locator('.vendor-currency-card')).toHaveCount(4);await page.locator('button[data-view=list]').click();await expect(page.locator('.vendor-currency-card')).toHaveCount(4);await expect(page.locator('#currency-vendor-search')).toHaveValue(prefix);
  await page.locator('#currency-vendor-search').fill(prefix+'A.USD');await expect(page.locator('.vendor-currency-card')).toHaveCount(1);const card=page.locator('.vendor-currency-card');await expect(card.locator('[data-name]')).toHaveText(prefix+'A.USD');await expect(card.locator('[data-rate]')).toContainText('Not configured');await card.locator('[data-bs-toggle=dropdown]').click();await card.locator('[data-action=edit]').click();
  await expect(page.locator('#vendor-currency-form input')).toHaveCount(1);await expect(page.locator('#vendor-currency-rate')).toHaveValue('');await expect(page.locator('#vendor-currency-identity')).toHaveText(prefix+'A.USD');await expect(page.locator('#vendor-currency-dialog [data-translation-toggle]')).toHaveCount(0);await page.locator('#vendor-currency-rate').fill('0');await page.locator('#vendor-currency-save').click();await expect(page.locator('#vendor-currency-status')).toContainText('greater than zero');await page.locator('#vendor-currency-rate').fill('20.5');await page.locator('#vendor-currency-save').click();await expect(page.locator('#vendor-currency-status')).toHaveText('Changes saved.');await footer(page,'vendor-currency-dialog');await close(page,'vendor-currency-dialog');await expect(card.locator('[data-rate]')).toHaveText('Rate: 20.5');await page.locator('button[data-view=grid]').click();await expect(card.locator('[data-rate]')).toHaveText('Rate: 20.5');
  await page.locator('#currency-vendor-search').fill(prefix);await expect(page.locator('.vendor-currency-card')).toHaveCount(4);await expect(page.locator('.vendor-currency-card.is-missing')).toHaveCount(3);await page.locator('#currency-refresh').click();await expect(page.locator('[data-currency-id="'+fixtures[0].id+'"] [data-rate]')).toHaveText('Rate: 20.5');
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.setAttribute('data-bs-theme',theme),theme);await page.screenshot({path:'artifacts/currencies-vendor-grid-'+theme+'.png'});await page.locator('button[data-view=list]').click();await page.screenshot({path:'artifacts/currencies-vendor-list-'+theme+'.png'});await page.locator('button[data-view=grid]').click();}
  await page.setViewportSize({width:390,height:844});await page.locator('button[data-view=list]').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/currencies-revision-mobile.png'});await page.reload();await expect(page.locator('#currencies-page')).toHaveAttribute('data-view','list');await page.locator('#currency-vendor-search').fill(prefix);await expect(page.locator('.vendor-currency-card.is-missing')).toHaveCount(3);await expect(page.locator('[data-currency-id="'+fixtures[0].id+'"] [data-rate]')).toHaveText('Rate: 20.5');await page.setViewportSize({width:1280,height:720});const persisted=page.locator('[data-currency-id="'+fixtures[0].id+'"]');await persisted.locator('[data-bs-toggle=dropdown]').click();await persisted.locator('[data-action=edit]').click();await expect(page.locator('#vendor-currency-rate')).toHaveValue('20.5');await page.locator('#vendor-currency-rate').fill('');await page.locator('#vendor-currency-save').click();await expect(page.locator('#vendor-currency-status')).toHaveText('Changes saved.');await close(page,'vendor-currency-dialog');await expect(persisted.locator('[data-rate]')).toContainText('Not configured');expect((await pool.query('SELECT * FROM vendor_currency_rates WHERE currency_id=$1',[fixtures[0].id])).rowCount).toBe(0);
  expect((await pool.query('SELECT * FROM currencies WHERE vendor_id=ANY($1::bigint[]) ORDER BY id',[vendors])).rows).toEqual(fixtures);expect(errors).toEqual([]);expect((await pool.query('SELECT rate,name,is_visible FROM frontend_currencies WHERE created_by=$1',[actor.id])).rows).toEqual([{rate:'15.75',name:prefix+' Updated',is_visible:true}]);
 }finally{await page.goto('about:blank');await pool.query('DELETE FROM frontend_currency_translations WHERE frontend_currency_id IN(SELECT id FROM frontend_currencies WHERE created_by=$1)',[actor.id]);await pool.query('DELETE FROM frontend_currencies WHERE created_by=$1',[actor.id]);if(vendors.length){await pool.query('DELETE FROM vendor_currency_rates WHERE vendor_id=ANY($1::bigint[])',[vendors]);await pool.query('DELETE FROM currencies WHERE vendor_id=ANY($1::bigint[])',[vendors]);await pool.query('DELETE FROM vendors WHERE id=ANY($1::bigint[])',[vendors]);}await pool.query('DELETE FROM cpanel_users WHERE id=$1',[actor.id]);}
});

test('Currency HTTP: CSRF, independent permissions, ownership and failed-save dirty state',async({page,context,baseURL})=>{
 const actor=await bootstrapSuperuser({name:'Currency security',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(actor.id);let vendor:string|undefined,currency:string|undefined;
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
 const call=async(method:string,path:string,body?:unknown,csrf=true)=>page.evaluate(async({method,path,body,token})=>{const response=await fetch('/cpanel/api/currencies'+path,{method,headers:{'Content-Type':'application/json',...(token?{'X-CSRF-Token':token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,data:await response.json().catch(()=>null)};},{method,path,body,token:csrf?session.session.csrf_token:''});
 const grants=async(keys:string[])=>{await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);for(const key of keys)await pool.query('INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,$2,to_jsonb(true))',[actor.id,key]);};
 try{
  await page.goto('/cpanel/currencies/frontend');expect((await call('POST','/frontend',{name:'CSRF',code:'C',symbol:'C'},false)).status).toBe(403);expect((await pool.query('SELECT * FROM frontend_currencies WHERE created_by=$1',[actor.id])).rowCount).toBe(0);
  const created=await call('POST','/frontend',{name:'HTTP fixture',code:'H',symbol:'H',rate:null});expect(created.status).toBe(201);const id=created.data.row.id;
  for(const [method,path,body] of [['PATCH','/frontend/'+id,{name:'No'}],['PUT','/frontend/'+id+'/translations',{translations:{ru:'No'}}]] as const)expect((await call(method,path,body,false)).status).toBe(403);
  vendor=(await pool.query("INSERT INTO vendors(name,url,username,password_encrypted,is_active) VALUES('Currency security','https://example.invalid/db','fixture',$1,false) RETURNING id",[new VendorCredentials(config.vendors.credentialsKey).encryptSecret('fixture')])).rows[0].id;currency=(await pool.query("INSERT INTO currencies(vendor_id,source_id,name) VALUES($1,'usd','USD') RETURNING id",[vendor])).rows[0].id;
  expect((await call('PUT','/vendors/'+vendor+'/'+currency,{rate:'1'},false)).status).toBe(403);expect((await pool.query('SELECT * FROM vendor_currency_rates WHERE currency_id=$1',[currency])).rowCount).toBe(0);
  expect((await call('PUT','/vendors/9223372036854775807/'+currency,{rate:'1'})).status).toBe(404);
  await grants(['currencies.frontend.view','currencies.vendor_rates.view']);expect((await call('GET','/frontend')).status).toBe(200);expect((await call('GET','/vendors')).status).toBe(200);expect((await call('PATCH','/frontend/'+id,{name:'No'})).status).toBe(403);expect((await call('PUT','/vendors/'+vendor+'/'+currency,{rate:'1'})).status).toBe(403);
  await page.reload();await expect(page.locator('#currency-add')).toHaveCount(0);await page.locator('#currency-search').fill('HTTP fixture');await expect(page.locator('.currency-card')).toHaveCount(1);await page.locator('.currency-card [data-bs-toggle=dropdown]').click();await page.locator('.currency-card [data-action=edit]').click();await expect(page.locator('#currency-name')).toBeDisabled();await expect(page.locator('#currency-save')).toBeDisabled();await close(page,'currency-dialog');
  await grants(['currencies.frontend.update']);expect((await call('PATCH','/frontend/'+id,{rate:'1'})).status).toBe(200);expect((await call('GET','/frontend')).status).toBe(403);expect((await call('PATCH','/frontend/'+id,{is_visible:true})).status).toBe(403);
  await grants(['currencies.frontend.visibility']);expect((await call('PATCH','/frontend/'+id,{is_visible:true})).status).toBe(200);expect((await call('PATCH','/frontend/'+id,{name:'No'})).status).toBe(403);
  await grants(['currencies.vendor_rates.update']);expect((await call('PUT','/vendors/'+vendor+'/'+currency,{rate:'1'})).status).toBe(200);expect((await call('GET','/vendors')).status).toBe(403);
  await grants(['currencies.frontend.view','currencies.frontend.update']);await page.goto('/cpanel/currencies/frontend');await page.locator('#currency-search').fill('HTTP fixture');await expect(page.locator('.currency-card')).toHaveCount(1);await page.locator('.currency-card [data-bs-toggle=dropdown]').click();await page.locator('.currency-card [data-action=edit]').click();await page.locator('#currency-name').fill('Unsaved retry');await grants(['currencies.frontend.view']);await page.locator('#currency-save').click();await expect(page.locator('#currency-save')).toBeEnabled();await expect(page.locator('#currency-name')).toHaveValue('Unsaved retry');expect((await pool.query('SELECT name FROM frontend_currencies WHERE id=$1',[id])).rows[0].name).toBe('HTTP fixture');await grants(['currencies.frontend.view','currencies.frontend.update']);await page.locator('#currency-save').click();await expect(page.locator('#currency-status')).toHaveText('Changes saved.');await close(page,'currency-dialog');
  await grants([]);expect((await page.goto('/cpanel/currencies/frontend'))!.status()).toBe(403);expect((await page.goto('/cpanel/currencies/vendors'))!.status()).toBe(403);
 }finally{await page.goto('about:blank');if(currency){await pool.query('DELETE FROM vendor_currency_rates WHERE currency_id=$1',[currency]);await pool.query('DELETE FROM currencies WHERE id=$1',[currency]);}if(vendor)await pool.query('DELETE FROM vendors WHERE id=$1',[vendor]);await pool.query('DELETE FROM frontend_currency_translations WHERE frontend_currency_id IN(SELECT id FROM frontend_currencies WHERE created_by=$1)',[actor.id]);await pool.query('DELETE FROM frontend_currencies WHERE created_by=$1',[actor.id]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[actor.id]);}
});
