import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
import {config} from '../src/config/env.js';
import {VendorCredentials} from '../src/vendors/credentials.js';
async function login(context:any,base:string,superuser=true){const actor=await bootstrapSuperuser({name:'Discounts test',email:randomUUID()+'@example.invalid',password:randomUUID()});if(!superuser)await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);const session=await sessions.create(actor.id);await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'&&!process.env.DISCOUNTS_VERIFY_URL?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(base).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1'&&!process.env.DISCOUNTS_VERIFY_URL,httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:base}]);return {id:actor.id,csrf:session.session.csrf_token};}
async function cleanup(id:string){await pool.query('DELETE FROM product_discounts WHERE discount_id IN(SELECT id FROM discounts WHERE created_by=$1)',[id]);await pool.query('DELETE FROM discount_translations WHERE discount_id IN(SELECT id FROM discounts WHERE created_by=$1)',[id]);await pool.query('DELETE FROM discounts WHERE created_by=$1',[id]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[id]);}
async function api(page:Page,method:string,path:string,body?:unknown,csrf?:string){return page.evaluate(async({method,path,body,csrf})=>{const response=await fetch('/cpanel/api/discounts'+path,{method,headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,data:await response.json().catch(()=>null)};},{method,path,body,csrf});}
const stored=async(id:string)=>(await pool.query('SELECT * FROM discounts WHERE id=$1',[id])).rows[0];
async function close(page:Page){await page.waitForFunction(()=>!(window as any).bootstrap.Modal.getInstance(document.getElementById('discount-dialog'))._isTransitioning);await page.locator('#discount-dialog .modal-header .btn-close').click();await expect(page.locator('#discount-dialog')).toBeHidden();}
async function save(page:Page,scope:string){const response=page.waitForResponse(r=>r.url().includes('/cpanel/api/discounts')&&r.request().method()!=='GET');await page.locator('#discount-save-'+scope).click();expect((await response).ok()).toBe(true);await expect(page.locator('#discount-save-'+scope)).toBeDisabled();}
async function edit(page:Page,id:string){const card=page.locator('[data-discount-id="'+id+'"]');await card.locator('[data-bs-toggle=dropdown]').click();await card.locator('[data-action=edit]').click();await expect(page.locator('#discount-dialog')).toBeVisible();}

test('Discount persistence: Create/Edit, independent scopes, reload, five actions, nullable dates and real count',async({page,context,baseURL})=>{
 test.setTimeout(90000);const base=process.env.DISCOUNTS_VERIFY_URL??baseURL!,actor=await login(context,base),prefix='Discount-'+randomUUID().slice(0,8),errors:string[]=[];let vendor:string|undefined,source:string|undefined;
 page.on('pageerror',error=>errors.push(error.message));
 try{
  expect((await page.goto(base+'/cpanel/discounts'))?.status()).toBe(200);await page.locator('#discount-add').click();await expect(page.locator('[data-tab=rules]')).toBeDisabled();await expect(page.locator('#discount-show-name')).toBeDisabled();
  await page.locator('#discount-name').fill(prefix);await page.locator('#discount-priority').fill('12');await save(page,'basic');const id=(await page.locator('#discount-dialog').getAttribute('data-entity-id'))!;expect(id).toMatch(/^\d+$/);await expect(page.locator('#discount-dialog')).toBeVisible();expect((await stored(id)).is_visible).toBe(false);expect((await stored(id)).is_visible_on_product).toBe(false);
  await page.locator('#discount-name').fill(prefix+' Changed');await page.locator('#discount-priority').fill('27');await page.locator('#discount-show-name').check();await page.locator('#discount-visibility').selectOption('visible');await page.locator('#discount-no-starts_at').uncheck();await page.locator('#discount-starts_at').fill('2027-05-01T10:15');await page.locator('#discount-no-ends_at').uncheck();await page.locator('#discount-ends_at').fill('2027-06-01T10:15');
  await page.locator('[data-tab=rules]').click();for(const kind of ['addAmount','addPercent','fixed','removeAmount','removePercent']){await page.locator('#discount-before-action').selectOption(kind);await page.locator('#discount-before-value').fill('15.25');await save(page,'rules');expect((await stored(id)).before_action).toBe(kind);expect((await stored(id)).priority).toBe(12);}
  await expect(page.locator('[data-state=basic]')).toHaveText('Unsaved');await page.locator('#discount-after-value').fill('4.75');await page.locator('[data-tab=basic]').click();await page.locator('[data-translation-toggle]').click();await page.locator('[data-translation-input=ru]').fill('Скидка');const translated=page.waitForResponse(r=>r.request().method()==='PUT'&&r.url().includes('/translations'));await page.locator('[data-save-field]').click();expect((await translated).ok()).toBe(true);expect((await stored(id)).after_value).toBe(null);
  await save(page,'basic');expect((await stored(id)).after_value).toBe(null);await expect(page.locator('[data-state=rules]')).toHaveText('Unsaved');expect((await stored(id)).is_visible_on_product).toBe(true);await page.locator('[data-tab=rules]').click();await save(page,'rules');await close(page);
  await page.reload();await page.locator('#discount-search').fill(prefix);await expect(page.locator('[data-discount-id="'+id+'"]')).toBeVisible();await edit(page,id);await expect(page.locator('#discount-name')).toHaveValue(prefix+' Changed');await expect(page.locator('#discount-priority')).toHaveValue('27');await expect(page.locator('#discount-starts_at')).toHaveValue('2027-05-01T10:15');await expect(page.locator('#discount-show-name')).toBeChecked();await page.locator('[data-translation-toggle]').click();await expect(page.locator('[data-translation-input=ru]')).toHaveValue('Скидка');
  await page.locator('[data-tab=rules]').click();await expect(page.locator('#discount-after-value')).toHaveValue('4.75');
  // Safe server failure leaves only Rules dirty; Basic remains saved.
  await page.locator('#discount-before-value').fill('101');let invalid=page.waitForResponse(r=>r.url().endsWith('/rules')&&r.request().method()==='PATCH');await page.locator('#discount-save-rules').click();expect((await invalid).status()).toBe(400);await expect(page.locator('[data-state=rules]')).toHaveText('Unsaved');expect((await stored(id)).before_value).toBe('15.25');await page.locator('#discount-before-value').fill('100');await save(page,'rules');
  await page.locator('[data-tab=basic]').click();await page.locator('#discount-no-starts_at').check();await page.locator('#discount-no-ends_at').check();await save(page,'basic');expect((await stored(id)).starts_at).toBe(null);await close(page);
  vendor=(await pool.query("INSERT INTO vendors(name,url,username,password_encrypted,is_active) VALUES('Discount count fixture','https://example.invalid/db','fixture',$1,false) RETURNING id",[new VendorCredentials(config.vendors.credentialsKey).encryptSecret('fixture')])).rows[0].id;
  source=(await pool.query("INSERT INTO source_products(vendor_id,source_id,name) VALUES($1,'discount-browser-count','Fixture') RETURNING id",[vendor])).rows[0].id;
  const product=(await pool.query('INSERT INTO products(source_product_id,name) VALUES($1,\'Fixture Product\') RETURNING id',[source])).rows[0].id;await pool.query('INSERT INTO product_discounts(product_id,discount_id) VALUES($1,$2)',[product,id]);
  await page.reload();await page.locator('#discount-search').fill(prefix);const card=page.locator('[data-discount-id="'+id+'"]');await expect(card.locator('[data-products]')).toHaveText('Products: 1');await page.locator('button[data-view=list]').click();await expect(card.locator('[data-products]')).toHaveText('Products: 1');await edit(page,id);await page.locator('[data-tab=products]').click();await expect(page.locator('#discount-product-count')).toHaveText('Products: 1');await expect(page.locator('#discount-dialog .modal-footer button:visible')).toHaveCount(1);await close(page);
  await card.locator('[data-bs-toggle=dropdown]').click();const toggle=page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().endsWith('/'+id));await card.locator('[data-action=visibility]').click();expect((await toggle).ok()).toBe(true);expect((await stored(id)).is_visible).toBe(false);await page.locator('#discount-filter').selectOption('visible');await expect(card).toHaveCount(0);await page.locator('#discount-filter').selectOption('hidden');await expect(card).toBeVisible();
  const before=await stored(id);for(const [method,path,body]of [['POST','',{name:'Denied',priority:1}],['PATCH','/'+id,{priority:99}],['PATCH','/'+id+'/rules',{before_action:'fixed',before_value:'1',after_action:'fixed',after_value:null}],['PUT','/'+id+'/translations',{translations:{en:'Denied'}}]] as const)expect((await api(page,method,path,body)).status).toBe(403);expect(await stored(id)).toEqual(before);
  for(const lang of ['tm','ru','en']){await context.addCookies([{name:'hormat_lang',value:lang,url:base}]);await page.reload();await page.locator('#discount-search').fill(prefix);await edit(page,id);await expect(page.locator('#discount-dialog')).not.toContainText('cpanel.');await close(page);}
  expect(errors).toEqual([]);
 }finally{await page.goto('about:blank');await cleanup(actor.id);if(source){await pool.query('DELETE FROM products WHERE source_product_id=$1',[source]);await pool.query('DELETE FROM source_products WHERE id=$1',[source]);}if(vendor)await pool.query('DELETE FROM vendors WHERE id=$1',[vendor]);}
});

test('Discount HTTP permission boundaries, revocation and safe payload validation',async({page,context,baseURL})=>{
 const base=process.env.DISCOUNTS_VERIFY_URL??baseURL!,actor=await login(context,base);
 try{
  await page.goto(base+'/cpanel/discounts');const result=await api(page,'POST','',{name:'Permission '+randomUUID(),priority:1},actor.csrf);expect(result.status).toBe(201);const id=result.data.row.id;
  const grant=async(...keys:string[])=>{await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);for(const key of keys)await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,$2,'true')",[actor.id,key]);};
  await grant('discounts.view');await page.reload();await expect(page.locator('#discount-add')).toHaveCount(0);await page.locator('#discount-search').fill(result.data.row.basic.name);await edit(page,id);await expect(page.locator('#discount-name')).toBeDisabled();await expect(page.locator('#discount-save-basic')).toBeDisabled();await close(page);expect((await api(page,'PATCH','/'+id,{priority:2},actor.csrf)).status).toBe(403);
  await grant('discounts.update');expect((await api(page,'GET','/'+id)).status).toBe(403);expect((await api(page,'PATCH','/'+id,{is_visible:true},actor.csrf)).status).toBe(403);expect((await api(page,'PATCH','/'+id,{is_visible_on_product:true},actor.csrf)).status).toBe(200);
  expect((await api(page,'PATCH','/'+id,{priority:3,id:'1'},actor.csrf)).status).toBe(400);expect((await api(page,'PATCH','/'+id,{starts_at:'2027-02-01T00:00:00Z',ends_at:'2027-01-01T00:00:00Z'},actor.csrf)).status).toBe(400);expect((await api(page,'PUT','/'+id+'/translations',{translations:{unknown:'Bad'}},actor.csrf)).status).toBe(400);
  await grant('discounts.visibility');expect((await api(page,'PATCH','/'+id,{is_visible:true},actor.csrf)).status).toBe(200);expect((await api(page,'PATCH','/'+id,{is_visible_on_product:false},actor.csrf)).status).toBe(403);
  await grant();expect((await page.goto(base+'/cpanel/discounts'))?.status()).toBe(403);
 }finally{await page.goto('about:blank');await cleanup(actor.id);}
});

test('Discount navigation enables only effective view access and preserves Source Products boundary',async({page,context,baseURL})=>{
 const base=process.env.DISCOUNTS_VERIFY_URL??baseURL!,actor=await login(context,base);
 try{
  await page.goto(base+'/cpanel');await expect(page.locator('aside a[href="/cpanel/discounts"]')).toHaveCount(1);
  await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'discounts.view','true')",[actor.id]);await page.reload();await expect(page.locator('aside a[href="/cpanel/discounts"]')).toHaveCount(1);await page.locator('aside a[href="/cpanel/discounts"]').click();await expect(page).toHaveURL(base+'/cpanel/discounts');
  await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[actor.id]);await page.goto(base+'/cpanel');await expect(page.locator('aside a[href="/cpanel/discounts"]')).toHaveCount(0);await expect(page.locator('aside a[href="/cpanel/source-products"]')).toHaveCount(0);expect((await page.goto(base+'/cpanel/discounts'))?.status()).toBe(403);
 }finally{await page.goto('about:blank');await cleanup(actor.id);}
});
