import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
test('shared HTML editor toolbar, translated paragraphs, server roundtrip and plain previews',async({page,context,baseURL})=>{
 const user=await bootstrapSuperuser({name:'HTML review',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id),name='HTML '+randomUUID();let id:string|undefined;
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const base=page.locator('[data-translatable-field=type-description] > .input-group .html-editor-area'),editor=base.locator('..');
 const select=async()=>base.evaluate(el=>{el.focus();const range=document.createRange();range.selectNodeContents(el);const s=getSelection();s!.removeAllRanges();s!.addRange(range);});
 const save=async()=>{await page.locator('#type-save').click();await expect(page.locator('#type-status')).toHaveText('Changes saved.');await expect(page.locator('#type-save')).toBeDisabled();};
 const close=async()=>{await page.waitForFunction(()=>!(window as any).bootstrap.Modal.getInstance(document.getElementById('type-dialog'))._isTransitioning);await page.locator('#type-dialog .modal-footer [data-bs-dismiss]').click();await expect(page.locator('#type-dialog')).toBeHidden();};
 try{
  await page.goto('/cpanel/payment-types');await page.locator('#type-search').fill(name);await page.locator('#type-add').click();await page.locator('#type-name').fill(name);
  await base.fill('Cash & card < 5');await save();await expect(base).toHaveText('Cash & card < 5');await base.fill('Format text');await select();for(const cmd of ['bold','italic','underline'])await editor.locator('[data-html-command='+cmd+']').click();expect(await base.innerHTML()).toMatch(/<(b|strong)>/);expect(await base.innerHTML()).toMatch(/<(i|em)>/);expect(await base.innerHTML()).toMatch(/<u>/);
  await select();page.once('dialog',dialog=>dialog.accept('https://example.com'));await editor.locator('[data-html-command=createLink]').click();await expect(base.locator('a')).toHaveAttribute('href','https://example.com');
  await save();id=await page.locator('#type-dialog').getAttribute('data-entity-id')??undefined;expect(id).toMatch(/^\d+$/);
  for(const [cmd,tag] of [['insertUnorderedList','ul'],['insertOrderedList','ol']]){await base.fill('List item');await select();await editor.locator('[data-html-command='+cmd+']').click();await expect(base.locator(tag+' li')).toHaveText('List item');}
  await editor.locator('[data-html-command=removeFormat]').click();expect(await base.innerHTML()).not.toMatch(/<(ul|ol|b|i|u|a)\b/);
  await base.evaluate(el=>{el.innerHTML='<p><b>Cash</b> and <i>card</i></p><ul><li><u>On arrival</u></li></ul><p><a href="https://example.com">Help</a></p>';el.dispatchEvent(new Event('input',{bubbles:true}));});await save();
  const field=page.locator('[data-translatable-field=type-description]');await field.locator('[data-translation-toggle]').click();const translated=field.locator('[data-translation-row=ru] .html-editor-area');await translated.fill('Первая строка');await translated.press('End');await translated.press('Enter');await translated.pressSequentially('Вторая строка');await field.locator('[data-save-field]').click();await expect(field.locator('[data-translation-status]')).toHaveText('Changes saved.');await close();
  await page.reload();await page.locator('#type-search').fill(name);const card=page.locator('.type-card[data-id="'+id+'"]');await expect(card.locator('[data-description]')).toContainText('Cash and card');await expect(card.locator('[data-description]')).not.toContainText('<p>');await page.locator('[data-view=list]').click();await expect(card.locator('[data-description]')).toContainText('On arrival');
  await card.locator('[data-bs-toggle]').click();await card.locator('[data-edit]').click();await expect(base.locator('b')).toHaveText('Cash');await expect(base.locator('a')).toHaveAttribute('href','https://example.com');await field.locator('[data-translation-toggle]').click();await expect(translated).toContainText('Вторая строка');
  const stored=(await pool.query('SELECT description FROM payment_types WHERE id=$1',[id])).rows[0].description;expect(stored).toContain('<b>Cash</b>');expect((await pool.query("SELECT description FROM payment_type_translations WHERE payment_type_id=$1 AND language_code='ru'",[id])).rows[0].description).toContain('Вторая строка');
  await editor.locator('[data-html-mode=html]').click();const source=editor.locator('.html-editor-source');await expect(source).toHaveValue(/<b>Cash<\/b>/);
  const manual='<div class="delivery-info" style="text-align:center"><img src="/media/example.png" alt="Delivery" style="max-width:120px" onerror="window.htmlAttack=1"><h3>Manual markup</h3><p onclick="window.htmlAttack=1" style="position:fixed;padding:10px">Safe</p><a href="javascript:alert(1)">Link</a><script>window.htmlAttack=1</script></div>';
  await source.fill(manual);await editor.locator('[data-html-mode=visual]').click();await expect(base.locator('div.delivery-info')).toBeVisible();await expect(base.locator('img')).toHaveAttribute('src','/media/example.png');await expect(base.locator('img')).not.toHaveAttribute('onerror');expect(await base.innerHTML()).not.toMatch(/onclick|javascript:|position:fixed|<script/);expect(await page.evaluate(()=>(window as any).htmlAttack)).toBeUndefined();
  await editor.locator('[data-html-mode=html]').click();await expect(source).toHaveValue(manual);expect((await pool.query('SELECT description FROM payment_types WHERE id=$1',[id])).rows[0].description).toBe(stored);await save();await expect(source).not.toHaveValue(/onclick|onerror|javascript:|<script/);
  const translatedEditor=translated.locator('..');await translatedEditor.locator('[data-html-mode=html]').click();await translatedEditor.locator('.html-editor-source').fill('<div class="ru-info" style="padding:8px"><strong>Ручной перевод</strong><img src="/media/ru.png"></div>');await translatedEditor.locator('[data-html-mode=visual]').click();await expect(translated.locator('strong')).toHaveText('Ручной перевод');await field.locator('[data-save-field]').click();await expect(field.locator('[data-translation-status]')).toHaveText('Changes saved.');await close();
  await page.reload();await page.locator('#type-search').fill(name);await expect(card).toBeVisible();await card.locator('[data-bs-toggle]').click();await card.locator('[data-edit]').click();await expect(base.locator('div.delivery-info')).toHaveAttribute('style','text-align:center');await expect(base.locator('img')).toHaveAttribute('style','max-width:120px');await field.locator('[data-translation-toggle]').click();await expect(translated.locator('strong')).toHaveText('Ручной перевод');
  await page.screenshot({path:'artifacts/html-description.png'});expect(errors).toEqual([]);
 }finally{await page.goto('about:blank');await pool.query('DELETE FROM payment_type_translations WHERE payment_type_id IN(SELECT id FROM payment_types WHERE created_by=$1)',[user.id]);await pool.query('DELETE FROM payment_types WHERE created_by=$1',[user.id]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});
