import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
async function close(page:Page){await page.waitForFunction(()=>!(window as any).bootstrap.Modal.getInstance(document.getElementById('language-dialog'))._isTransitioning);await page.locator('#language-dialog .modal-footer [data-bs-dismiss]').click();await expect(page.locator('#language-dialog')).toBeHidden();await expect(page.locator('.modal-backdrop')).toHaveCount(0);}
async function action(page:Page,code:string,action:string){const card=page.locator('[data-language-code="'+code+'"].language-card');await card.locator('[data-bs-toggle=dropdown]').click();await card.locator('[data-action='+action+']').click();}

test('Languages activation: persistent Create/Edit, Grid/List, status, default safeguards and cookie/cache smoke',async({page,context,baseURL})=>{
 const user=await bootstrapSuperuser({name:'Language activation',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id),code='xx-'+randomUUID().slice(0,16);
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
 const before=(await pool.query('SELECT * FROM languages ORDER BY code')).rows,defaultCode=before.find(row=>row.is_default).code,translations=(await pool.query('SELECT * FROM interface_translations ORDER BY language_code,translation_key')).rows;
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const card=(key:string)=>page.locator('.language-card[data-language-code="'+key+'"]');
 try{
  expect((await page.goto('/cpanel/languages'))!.status()).toBe(200);await expect(page.locator('#languages-filter')).toHaveValue('all');await expect(page.locator('.language-card')).toHaveCount(before.length);await expect(page.locator('.language-card [data-default].text-bg-primary')).toHaveCount(1);
  await page.locator('#languages-search').fill('Русский');await expect(page.locator('.language-card')).toHaveCount(1);await page.locator('button[data-view=list]').click();await expect(card('ru')).toBeVisible();await expect(page.locator('#languages-search')).toHaveValue('Русский');await page.locator('#languages-search').fill('');await expect(page.locator('.language-card')).toHaveCount(before.length);
  await card(defaultCode).locator('[data-bs-toggle=dropdown]').click();await expect(card(defaultCode).locator('[data-action=status]')).toBeDisabled();await expect(card(defaultCode).locator('[data-action=default]')).toBeHidden();await page.keyboard.press('Escape');await action(page,defaultCode,'edit');await expect(page.locator('#language-code')).toHaveAttribute('readonly','');await expect(page.locator('#language-active')).toBeDisabled();await expect(page.locator('#language-default')).toBeDisabled();await close(page);
  await page.locator('#languages-add').click();await page.locator('#language-code').fill('tm');await page.locator('#language-name').fill('Duplicate');await page.locator('#language-save').click();await expect(page.locator('#language-status')).toContainText('already exists');await page.locator('#language-code').fill(code);await page.locator('#language-name').fill('Review language');await page.locator('#language-sort').fill('15');await page.locator('#language-save').click();await expect(page.locator('#language-dialog')).toHaveAttribute('data-language-code',code);await expect(page.locator('#language-title')).toHaveText('Edit Language');await expect(page.locator('#language-code')).toHaveAttribute('readonly','');await expect(page.locator('#language-active')).not.toBeChecked();await expect(page.locator('#language-default')).not.toBeChecked();await expect(page.locator('#shell-language option[value="'+code+'"]')).toHaveCount(0);
  const buttons=page.locator('#language-dialog .modal-footer button');const a=(await buttons.nth(0).boundingBox())!,b=(await buttons.nth(1).boundingBox())!;expect(Math.abs(a.y+a.height/2-b.y-b.height/2)).toBeLessThan(2);
  await page.locator('#language-name').fill('Persisted language');await page.locator('#language-sort').fill('-1');await page.locator('#language-save').click();await expect(page.locator('#language-status')).toHaveText('Language changes saved.');await close(page);await page.reload();await expect(card(code)).toContainText('Persisted language');await expect(page.locator('.language-card').first()).toHaveAttribute('data-language-code',code);await expect(card(code)).toHaveClass(/is-inactive/);
  await page.locator('#languages-filter').selectOption('inactive');await expect(card(code)).toBeVisible();await page.locator('button[data-view=grid]').click();await expect(page.locator('#languages-filter')).toHaveValue('inactive');await page.locator('#languages-filter').selectOption('all');await action(page,code,'status');await expect(card(code)).not.toHaveClass(/is-inactive/);await expect(page.locator('#shell-language option[value="'+code+'"]')).toHaveCount(1);
  await action(page,code,'default');await expect(page.locator('#languages-feedback')).toContainText('complete every interface key');expect((await pool.query('SELECT code FROM languages WHERE is_default')).rows[0].code).toBe(defaultCode);
  // A newly active language without overrides uses the current Default, not visible keys.
  await page.locator('#shell-language').selectOption(code);await page.waitForFunction(code=>document.documentElement.lang===code,code);const expected=(await pool.query("SELECT translation_value FROM interface_translations WHERE language_code=$1 AND translation_key='cpanel.navigation.languages'",[defaultCode])).rows[0].translation_value;await expect(page.locator('h1')).toHaveText(expected);
  await action(page,code,'status');await page.waitForFunction(code=>document.documentElement.lang===code,defaultCode);await expect(page.locator('#shell-language option[value="'+code+'"]')).toHaveCount(0);await expect(card(code)).toHaveClass(/is-inactive/);expect((await context.cookies()).find(c=>c.name==='hormat_lang')?.value).toBe(code);
  await page.locator('#shell-language').selectOption('en');await page.waitForFunction(()=>document.documentElement.lang==='en');await expect(page.locator('[data-action=delete]')).toHaveCount(0);
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.setAttribute('data-bs-theme',theme),theme);await page.locator('button[data-view=list]').click();await page.screenshot({path:'artifacts/languages-activated-'+theme+'.png'});}
  expect((await pool.query('SELECT * FROM languages WHERE code<>$1 ORDER BY code',[code])).rows).toEqual(before);expect((await pool.query('SELECT * FROM interface_translations ORDER BY language_code,translation_key')).rows).toEqual(translations);expect(errors).toEqual([]);
 }finally{await page.goto('about:blank');await pool.query('DELETE FROM interface_translations WHERE language_code=$1',[code]);await pool.query('DELETE FROM languages WHERE code=$1',[code]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});

test('Languages HTTP: CSRF, immutable code, independent permissions and retryable unsaved state',async({page,context,baseURL})=>{
 const user=await bootstrapSuperuser({name:'Language HTTP',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id),code='xx-'+randomUUID().slice(0,16);
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
 const call=async(method:string,path:string,body?:unknown,csrf=true)=>page.evaluate(async({method,path,body,token})=>{const response=await fetch('/cpanel/api/languages'+path,{method,headers:{'Content-Type':'application/json',...(token?{'X-CSRF-Token':token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,data:await response.json().catch(()=>null)};},{method,path,body,token:csrf?session.session.csrf_token:''});
 const grants=async(keys:string[])=>{await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[user.id]);for(const key of keys)await pool.query('INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,$2,to_jsonb(true))',[user.id,key]);};
 try{
  await page.goto('/cpanel/languages');expect((await call('POST','',{code,name:'HTTP language'},false)).status).toBe(403);expect((await call('POST','',{code,name:'HTTP language'})).status).toBe(201);
  for(const [method,path,body]of [['PATCH','/'+code,{name:'Bad'}],['POST','/'+code+'/status',{is_active:true}],['POST','/'+code+'/default',{}]]as const)expect((await call(method,path,body,false)).status).toBe(403);
  expect((await call('PATCH','/'+code,{code:'changed'})).status).toBe(400);expect((await call('PATCH','/'+code,{is_active:'true'})).status).toBe(400);
  await grants(['languages.view']);await page.reload();await expect(page.locator('#languages-add')).toHaveCount(0);await action(page,code,'edit');await expect(page.locator('#language-name')).toBeDisabled();await expect(page.locator('#language-active')).toBeDisabled();await expect(page.locator('#language-default')).toBeDisabled();await close(page);expect((await call('PATCH','/'+code,{name:'No'})).status).toBe(403);
  await grants(['languages.update']);expect((await call('PATCH','/'+code,{name:'HTTP edited'})).status).toBe(200);expect((await call('PATCH','/'+code,{is_active:true})).status).toBe(403);expect((await call('PATCH','/'+code,{is_default:true})).status).toBe(403);expect((await call('GET','')).status).toBe(403);
  await grants(['languages.status']);expect((await call('POST','/'+code+'/status',{is_active:true})).status).toBe(200);expect((await call('PATCH','/'+code,{name:'No'})).status).toBe(403);expect((await call('POST','/'+code+'/default',{})).status).toBe(403);
  await grants(['languages.default']);expect((await call('POST','/'+code+'/default',{})).data.code).toBe('LANGUAGE_TRANSLATIONS_INCOMPLETE');expect((await call('POST','/'+code+'/status',{is_active:false})).status).toBe(403);
  await grants(['languages.view','languages.update']);await page.goto('/cpanel/languages');await action(page,code,'edit');await page.locator('#language-name').fill('Retry saved');await grants(['languages.view']);await page.locator('#language-save').click();await expect(page.locator('#language-save')).toBeEnabled();await expect(page.locator('#language-name')).toHaveValue('Retry saved');expect((await pool.query('SELECT display_name FROM languages WHERE code=$1',[code])).rows[0].display_name).toBe('HTTP edited');await grants(['languages.view','languages.update']);await page.locator('#language-save').click();await expect(page.locator('#language-status')).toHaveText('Language changes saved.');await close(page);
  await grants([]);expect((await page.goto('/cpanel/languages'))!.status()).toBe(403);
 }finally{await page.goto('about:blank');await pool.query('DELETE FROM interface_translations WHERE language_code=$1',[code]);await pool.query('DELETE FROM languages WHERE code=$1',[code]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});
