import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
const folder='option-types-'+randomUUID(),root=path.resolve('.test-media',folder),pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8x8AAAAASUVORK5CYII=','base64');
test.beforeAll(async()=>{await mkdir(root,{recursive:true});await writeFile(path.join(root,'icon.png'),pixel);});
test.afterAll(async()=>{await rm(root,{recursive:true,force:true});});
for(const mode of ['payment','delivery'])test(mode+' activation: real Create/Edit, translations, icon, defaults, price, reload and CSRF',async({page,context,baseURL})=>{
 const user=await bootstrapSuperuser({name:'Type activation',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id),route='/cpanel/'+mode+'-types',table=mode+'_types',name='Review '+randomUUID();
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 const close=async()=>{await page.waitForFunction(()=>!(window as any).bootstrap.Modal.getInstance(document.getElementById('type-dialog'))._isTransitioning);await page.locator('#type-dialog .modal-content > .modal-footer [data-bs-dismiss]').click();await expect(page.locator('#type-dialog')).toBeHidden();};
 const call=async(method:string,path:string,body?:unknown,csrf=true)=>page.evaluate(async({method,path,body,token,mode})=>{const r=await fetch('/cpanel/api/'+mode+'-types'+path,{method,headers:{'Content-Type':'application/json',...(token?{'X-CSRF-Token':token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,data:await r.json().catch(()=>null)};},{method,path,body,token:csrf?session.session.csrf_token:'',mode});
 const save=async()=>{await page.locator('#type-save').click();await expect(page.locator('#type-save')).toBeDisabled();await expect(page.locator('#type-status')).toHaveText('Changes saved.');};
 const originalDefault=(await pool.query(`SELECT id FROM ${table} WHERE is_default`)).rows[0]?.id;
 try{
  expect((await page.goto(route))!.status()).toBe(200);await expect(page.locator('aside a[href="'+route+'"]')).toHaveCount(1);await expect(page.locator('#type-filter')).toHaveValue('all');await page.locator('#type-search').fill(name);
  await page.locator('#type-add').click();await expect(page.locator('#type-select-icon')).toBeDisabled();await expect(page.locator('#type-default')).toBeDisabled();await expect(page.locator('#type-default')).not.toBeChecked();await expect(page.locator('#type-visible')).toHaveValue('hidden');
  await page.locator('#type-name').fill(name);await page.locator('[data-translatable-field=type-description] > .input-group .html-editor-area').fill('Stored description');await page.locator('#type-sort').fill('-5');await save();await expect(page.locator('#type-dialog')).toHaveAttribute('data-entity-id',/^\d+$/);const id=(await page.locator('#type-dialog').getAttribute('data-entity-id'))!,card=page.locator('.type-card[data-id="'+id+'"]');
  const footer=page.locator('#type-dialog .modal-content > .modal-footer'),a=(await footer.locator('button').nth(0).boundingBox())!,b=(await footer.locator('button').nth(1).boundingBox())!;expect(Math.abs(a.y+a.height/2-b.y-b.height/2)).toBeLessThan(2);
  for(const field of ['name','description']){const component=page.locator('[data-translatable-field=type-'+field+']');await component.locator('[data-translation-toggle]').click();await (field==='description'?component.locator('[data-translation-row=ru] .html-editor-area'):component.locator('[data-translation-input=ru]')).fill('Перевод '+field);await component.locator('[data-save-field]').click();await expect(component.locator('[data-translation-status]')).toHaveText('Changes saved.');await component.locator('[data-translation-toggle]').click();}
  await page.locator('#type-select-icon').click();await page.locator('[data-picker-path="'+folder+'"]').click();await page.locator('[data-picker-path="'+folder+'/icon.png"]').click();await page.locator('[data-picker-confirm]').click();await save();
  if(mode==='delivery'){await page.locator('#type-free').uncheck();await page.locator('#type-price').fill('12.75');await save();await expect(card.locator('[data-price]')).toHaveText('12.75');expect((await pool.query(`SELECT price FROM ${table} WHERE id=$1`,[id])).rows[0].price).toBe('12.75');await page.locator('#type-free').check();await save();await expect(card.locator('[data-price]')).toHaveText('Free');}
  if(!originalDefault){await page.locator('#type-default').check();await expect(page.locator('#type-visible')).toHaveValue('visible');await save();await expect(card.locator('[data-default]')).toBeVisible();expect((await call('PATCH','/'+id,{is_visible:false})).status).toBe(409);}
  else{await page.locator('#type-visible').selectOption('visible');await save();}
  await close();await page.reload();await page.locator('#type-search').fill(name);await expect(card).toBeVisible();await page.locator('button[data-view=list]').click();await page.locator('#type-filter').selectOption('visible');await expect(card).toBeVisible();await page.locator('button[data-view=grid]').click();await expect(page.locator('#type-search')).toHaveValue(name);await expect(page.locator('#type-filter')).toHaveValue('visible');
  await card.locator('[data-bs-toggle]').click();await card.locator('[data-edit]').click();await expect(page.locator('[data-translatable-field=type-description] > .input-group .html-editor-area')).toHaveText('Stored description');await expect(page.locator('#type-icon-preview img')).toHaveCount(1);await expect(page.locator('#type-sort')).toHaveValue('-5');await expect(page.locator('[data-translatable-field=type-name] [data-translation-count]')).toHaveText('1 / 3');if(mode==='delivery')await expect(page.locator('#type-price')).toHaveValue('0');
  if(!originalDefault){await page.locator('#type-default').uncheck();await save();}await page.locator('#type-clear-icon').click();await save();expect(await readFile(path.join(root,'icon.png'))).toEqual(pixel);await close();
  await expect(page.locator('.modal-backdrop')).toHaveCount(0);
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.setAttribute('data-bs-theme',theme),theme);await page.screenshot({path:'artifacts/'+mode+'-types-activated-'+theme+'.png'});}
  expect((await call('POST','',{name:'No'},false)).status).toBe(403);expect((await call('PATCH','/'+id,{name:'No'},false)).status).toBe(403);expect((await call('PUT','/'+id+'/translations',{field:'name',translations:{ru:'No'}},false)).status).toBe(403);
  await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[user.id]);await pool.query('INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,$2,to_jsonb(true))',[user.id,table+'.view']);await page.reload();await page.locator('#type-search').fill(name);await expect(card).toBeVisible();await expect(page.locator('#type-add')).toHaveCount(0);await card.locator('[data-bs-toggle]').click();await card.locator('[data-edit]').click();await expect(page.locator('#type-name')).toBeDisabled();await expect(page.locator('#type-default')).toBeDisabled();await close();expect((await call('PATCH','/'+id,{is_default:true})).status).toBe(403);await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[user.id]);expect((await page.goto(route))!.status()).toBe(403);expect(errors).toEqual([]);
 }finally{await page.goto('about:blank');await pool.query(`DELETE FROM ${mode}_type_translations WHERE ${mode}_type_id IN(SELECT id FROM ${table} WHERE created_by=$1)`,[user.id]);await pool.query(`DELETE FROM ${table} WHERE created_by=$1`,[user.id]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});
