import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile,rm,readFile} from 'node:fs/promises';
import path from 'node:path';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
import {sourceBrowserFixture} from './fixtures/source-browser.js';
async function post(page:Page,url:string,body:unknown,csrf=true){return page.evaluate(async({url,body,csrf})=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':document.querySelector<HTMLElement>('[data-csrf]')!.dataset.csrf!}:{})},body:JSON.stringify(body)});return r.status;},{url,body,csrf});}
test('persistent Product Edit: independent scopes, HTML, discounts, real Gallery, reload and safe failures',async({page,context,baseURL})=>{
 test.setTimeout(90000);
 const fixture=await sourceBrowserFixture(pool),user=await bootstrapSuperuser({name:'Products activation',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id);
 const prefix='product-ui-'+randomUUID(),folder=path.resolve('.test-media',prefix),discountIds:string[]=[];
 await mkdir(folder,{recursive:true});const pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8x8AAAAASUVORK5CYII=','base64');for(const f of ['A.png','B.png','C.png'])await writeFile(path.join(folder,f),pixel);
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const dialog=page.locator('#product-dialog');
 const tab=(key:string)=>dialog.locator('[data-tab='+key+']').click();const save=async()=>{const done=page.waitForResponse(r=>r.url().includes('/api/products/')&&r.request().method()==='POST'&&!r.url().endsWith('/preview'));await dialog.locator('#product-save').click();expect((await done).status()).toBe(200);await expect(dialog.locator('#product-save')).toBeDisabled();};
 let id='';
 try{
  id=(await pool.query('SELECT id FROM products WHERE source_product_id=$1 ORDER BY id',[fixture.ids[0]])).rows[0].id;
  await pool.query('UPDATE source_products SET price=12 WHERE id=$1',[fixture.ids[0]]);await pool.query('INSERT INTO vendor_currency_rates(vendor_id,currency_id,rate) VALUES($1,$2,20)',[fixture.vendors[0],fixture.currency]);
  for(const priority of [10,30])discountIds.push((await pool.query('INSERT INTO discounts(name,priority) VALUES($1,$2) RETURNING id',[prefix+' '+priority,priority])).rows[0].id);
  await page.goto('/cpanel/products');await page.locator('[data-product-edit="'+id+'"]').click();await expect(dialog).toHaveAttribute('data-mode','edit');const source=await dialog.locator('#product-source-name').textContent();
  await dialog.locator('#product-name').fill('');await tab('seo');await dialog.locator('#product-slug').fill(prefix);await dialog.locator('#product-seo-title').fill('SEO');await save();await tab('basic');await expect(dialog.locator('#product-name')).toHaveValue('');await dialog.locator('#product-name').fill('Unsaved Basic');await expect(dialog.locator('#product-save')).toBeEnabled();await save();
  const nameField=dialog.locator('[data-translatable-field=product-name]');await nameField.locator('[data-translation-toggle]').click();await nameField.locator('[data-translation-input=ru]').fill('Товар');await nameField.locator('[data-save-field]').click();await expect(nameField.locator('[data-save-field]')).toBeDisabled();
  await tab('description');const html=dialog.locator('[data-translatable-field=product-description] > .input-group .html-editor');await html.locator('[data-html-mode=html]').click();await html.locator('.html-editor-source').fill('<div class="example"><b>Product HTML</b><script>alert(1)</script></div>');await save();await html.locator('[data-html-mode=visual]').click();await expect(html.locator('.html-editor-area b')).toHaveText('Product HTML');expect(await html.locator('.html-editor-area').innerHTML()).not.toContain('script');
  await tab('visibility');await dialog.locator('#product-showStock').check();await dialog.locator('#product-hideStock').check();await save();await expect(dialog.locator('#product-diagnostic li')).toHaveCount(6);
  await tab('priceRules');await dialog.locator('#product-rule').selectOption('addPercent');await dialog.locator('#product-rule-value').fill('25');await expect(dialog.locator('#product-price-preview')).toContainText('300');await save();
  await tab('discounts');for(const priority of [10,30]){const input=dialog.locator('#product-discount');await input.click();await input.fill(prefix);await dialog.locator('#product-discount-options [role=option]').filter({hasText:prefix+' '+priority}).click();await expect(input).toHaveValue('');}await expect(dialog.locator('#product-discounts article').first()).toContainText(prefix+' 30');await expect(dialog.locator('#product-save')).toBeHidden();const detached=dialog.locator('#product-discounts article').last();await detached.locator('[data-bs-toggle]').click();await detached.getByRole('button',{name:'Detach Discount',exact:true}).click();await expect(dialog.locator('#product-discounts article')).toHaveCount(1);
  await tab('gallery');await dialog.locator('#content-add-media').click();const picker=page.locator('[data-media-picker]');await expect(picker).toBeVisible();await picker.locator('[data-picker-path="'+prefix+'"]').dblclick();for(const f of ['A.png','B.png','C.png'])await picker.locator('[data-picker-path="'+prefix+'/'+f+'"]').click();await picker.locator('[data-picker-confirm]').click();await expect(dialog.locator('.gallery-card')).toHaveCount(3);
  const action=async(name:string,label:string)=>{const card=dialog.locator('.gallery-card').filter({has:page.locator('p',{hasText:name})});await card.locator('[data-bs-toggle]').click();await card.getByRole('button',{name:label,exact:true}).click();};
  await action('B.png','Set as Primary');await action('B.png','Move earlier');await save();await expect(dialog.locator('.gallery-card').first()).toContainText('B.png');await expect(dialog.locator('.gallery-card').first().locator('.badge')).toHaveText('Primary');
  await dialog.locator('.modal-footer [data-bs-dismiss]').click();await page.reload();await page.locator('[data-product-edit="'+id+'"]').click();await expect(dialog.locator('#product-name')).toHaveValue('Unsaved Basic');await expect(dialog.locator('#product-source-name')).toHaveText(source!);await tab('seo');await expect(dialog.locator('#product-slug')).toHaveValue(prefix);await tab('gallery');await expect(dialog.locator('.gallery-card').first()).toContainText('B.png');await expect(dialog.locator('.gallery-card .badge')).toHaveCount(1);await action('B.png','Remove from Gallery');await save();await expect(dialog.locator('#product-no-primary')).toBeVisible();expect(await readFile(path.join(folder,'B.png'))).toEqual(pixel);
  const row=(await pool.query('SELECT * FROM products WHERE id=$1',[id])).rows[0];expect(row.source_product_id).toBe(fixture.ids[0]);expect(row.show_as_in_stock).toBe(true);expect(row.hide_when_out_of_stock).toBe(true);expect(row.seo_title).toBe('SEO');expect(row.description_html).not.toContain('script');expect((await pool.query('SELECT name FROM product_translations WHERE product_id=$1 AND language_code=$2',[id,'ru'])).rows[0].name).toBe('Товар');
  await tab('description');await dialog.locator('#product-short-description').fill('Retry draft');await page.route('**/api/products/'+id+'/description',route=>route.fulfill({status:500,json:{success:false,code:'PRODUCT_SAVE_FAILED'}}));await dialog.locator('#product-save').click();await expect(dialog.locator('#product-status')).toHaveText(await page.locator('[data-product-label=error]').textContent()??'');await expect(dialog.locator('#product-short-description')).toHaveValue('Retry draft');await expect(dialog.locator('#product-save')).toBeEnabled();await page.unroute('**/api/products/'+id+'/description');await save();
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.bsTheme=theme,theme);await page.screenshot({path:'artifacts/products-activated-'+theme+'.png'});}await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
 }finally{await page.goto('about:blank').catch(()=>{});await pool.query('DELETE FROM vendor_currency_rates WHERE vendor_id=ANY($1::bigint[])',[fixture.vendors]);await fixture.cleanup();await pool.query('DELETE FROM discounts WHERE id=ANY($1::bigint[])',[discountIds]);await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);await rm(folder,{recursive:true,force:true});}
});
test('Product HTTP permissions, CSRF and immutable/malicious field protection',async({page,context,baseURL})=>{
 const fixture=await sourceBrowserFixture(pool),user=await bootstrapSuperuser({name:'Product viewer',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id);const id=(await pool.query('SELECT id FROM products WHERE source_product_id=$1 ORDER BY id',[fixture.ids[0]])).rows[0].id;
 try{
  await page.goto('/cpanel/products');expect(new URL(page.url()).pathname).toBe('/cpanel/login');await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[user.id]);await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'}]);expect((await page.goto('/cpanel/products'))?.status()).toBe(403);
  await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'products.view','true')",[user.id]);await page.goto('/cpanel/products');await expect(page.locator('#product-add')).toBeDisabled();await page.locator('[data-product-edit="'+id+'"]').click();await expect(page.locator('#product-name')).toBeDisabled();expect(await post(page,'/cpanel/api/products/'+id+'/basic',{name:'Forbidden'})).toBe(403);
  await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'products.update','true'),($1,'products.create','true')",[user.id]);expect(await post(page,'/cpanel/api/products/'+id+'/basic',{name:'No CSRF'},false)).toBe(403);expect(await post(page,'/cpanel/api/products',{source_product_id:fixture.ids[0],name:'No CSRF'},false)).toBe(403);expect(await post(page,'/cpanel/api/products/'+id+'/basic',{is_visible:true})).toBe(403);expect(await post(page,'/cpanel/api/products/'+id+'/basic',{source_product_id:fixture.ids[1]})).toBe(400);expect(await post(page,'/cpanel/api/products/'+id+'/seo',{created_by:user.id})).toBe(400);expect((await pool.query('SELECT name FROM products WHERE id=$1',[id])).rows[0].name).toBe('Fixture Product');
 }finally{await page.goto('about:blank').catch(()=>{});await fixture.cleanup();await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});
