import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
test('Products UI: create, independent scopes, source, rules, discounts, Gallery and responsive themes',async({page,context,baseURL})=>{
 const user=await bootstrapSuperuser({name:'Products UI review',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id);
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const tab=(key:string)=>page.locator('[data-tab='+key+']').click(),save=async()=>{await page.locator('#product-save').click();await expect(page.locator('#product-save')).toBeDisabled();};
 const choice=(n:number)=>page.locator('#product-choice-items button').nth(n).click();
 const before=(await pool.query('SELECT count(*) FROM products')).rows[0].count;
 try{
  expect((await page.goto('/cpanel/products'))?.status()).toBe(200);await expect(page.locator('.product-card')).toHaveCount(3);
  await page.locator('[data-view=list]').click();await expect(page.locator('#products-results')).toHaveAttribute('data-view','list');await page.locator('[data-view=grid]').click();await page.locator('#products-search').fill('impossible record');await expect(page.locator('#products-empty')).toBeVisible();await page.locator('#products-search').fill('');await page.locator('#products-filter-visibility').selectOption('visible');await expect(page.locator('.product-card')).toHaveCount(1);await page.locator('#products-filter-visibility').selectOption('all');
  await page.locator('#product-add').click();await expect(page.locator('[data-tab=seo]')).toBeDisabled();await page.locator('#product-save').click();await expect(page.locator('#product-status')).not.toBeEmpty();await page.locator('#product-name').fill('Review Product');await page.locator('#product-select-source').click();await expect(page.locator('#product-choice-items button').first()).toBeDisabled();await page.locator('#product-choice-search').fill('4');await choice(0);await save();await expect(page.locator('#product-dialog')).toBeVisible();await expect(page.locator('#product-title')).toContainText('Review Product');await expect(page.locator('#product-select-source')).toBeHidden();await expect(page.locator('#product-visible')).not.toBeChecked();await expect(page.locator('[data-tab=seo]')).toBeEnabled();
  await page.locator('#product-name').fill('Unsaved Basic');await tab('seo');await page.locator('#product-slug').fill('review-product');await page.locator('#product-seo-title').fill('SEO');await save();await tab('basic');await expect(page.locator('#product-name')).toHaveValue('Unsaved Basic');await expect(page.locator('#product-save')).toBeEnabled();await save();
  const nameField=page.locator('[data-translatable-field=product-name]');await nameField.locator('[data-translation-toggle]').click();await nameField.locator('[data-translation-input=ru]').fill('Товар');await nameField.locator('[data-save-field]').click();await expect(nameField.locator('[data-save-field]')).toBeDisabled();
  await tab('description');const html=page.locator('[data-translatable-field=product-description] > .input-group .html-editor');await html.locator('[data-html-mode=html]').click();await html.locator('.html-editor-source').fill('<div class="example"><b>Product HTML</b><script>alert(1)</script></div>');await html.locator('[data-html-mode=visual]').click();await expect(html.locator('.html-editor-area b')).toHaveText('Product HTML');await save();expect(await html.locator('.html-editor-area').innerHTML()).not.toContain('script');
  await tab('visibility');await page.locator('#product-showStock').check();await page.locator('#product-hideStock').check();await expect(page.locator('#product-showStock')).toBeChecked();await expect(page.locator('#product-diagnostic li')).toHaveCount(7);await save();
  await tab('priceRules');await page.locator('#product-rule').selectOption('addPercent');await page.locator('#product-rule-value').fill('25');await expect(page.locator('#product-price-preview')).toContainText('375');await save();
  await tab('discounts');await page.locator('#product-attach').click();await choice(2);await page.locator('#product-attach').click();await expect(page.locator('#product-choice-items button').nth(2)).toBeDisabled();await choice(0);await expect(page.locator('#product-discounts article').first()).toContainText('100');await expect(page.locator('#product-discounts article').nth(1)).toContainText('90');await save();await page.locator('#product-discounts article').nth(1).getByRole('button').click();await expect(page.locator('#product-discounts article')).toHaveCount(1);await save();
  // Controlled picker API fixture: uses the actual reusable Picker, no disk writes.
  const media=['A','B','C'].map(name=>({name:name+'.png',path:name+'.png',type:'image',url:'/media/'+name+'.png',image:true,folder:false,temporary:false,parent:''}));
  await page.route('**/cpanel/media?**',route=>route.fulfill({contentType:'text/html',body:media.map(item=>'<div data-entry="'+JSON.stringify(item).replaceAll('"','&quot;')+'"></div>').join('')}));
  await page.route('**/cpanel/api/media/details?**',route=>route.fulfill({json:{item:media.find(item=>item.path===new URL(route.request().url()).searchParams.get('path'))}}));
  await tab('gallery');await expect(page.locator('#product-no-primary')).toBeVisible();
  await page.locator('#content-add-media').click();await expect(page.locator('[data-media-picker]')).toBeVisible();for(const item of media)await page.locator('[data-picker-path="'+item.path+'"]').click();await page.locator('[data-picker-confirm]').click();await expect(page.locator('.gallery-card')).toHaveCount(3);
  const action=async(name:string,label:string)=>{const card=page.locator('.gallery-card').filter({has:page.locator('p',{hasText:name})});await card.locator('[data-bs-toggle]').click();await card.getByRole('button',{name:label,exact:true}).click();};
  await action('B.png','Set as Primary');await expect(page.locator('.gallery-card').filter({hasText:'B.png'}).locator('.badge')).toHaveText('Primary');await action('B.png','Move earlier');await expect(page.locator('.gallery-card').first()).toContainText('B.png');await expect(page.locator('.gallery-card').first().locator('.badge')).toHaveText('Primary');await save();
  await action('A.png','Remove from Gallery');await expect(page.locator('.gallery-card .badge')).toHaveCount(1);await action('B.png','Remove from Gallery');await expect(page.locator('#product-no-primary')).toBeVisible();await expect(page.locator('.gallery-card')).toHaveCount(1);await save();
  await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>document.documentElement.dataset.bsTheme='dark');await page.screenshot({path:'artifacts/products-dark.png'});await page.evaluate(()=>document.documentElement.dataset.bsTheme='light');await tab('description');await page.screenshot({path:'artifacts/products-light.png'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/products-mobile.png'});
  await page.locator('#product-short-description').fill('Unsaved description');await tab('seo');await tab('description');await expect(page.locator('#product-short-description')).toHaveValue('Unsaved description');await page.locator('#product-dialog .modal-footer [data-bs-dismiss]').click();await expect(page.locator('#product-discard')).toBeVisible();await page.locator('#product-keep').click();
  await page.route('**/cpanel/api/html-preview',route=>route.fulfill({status:500,json:{success:false}}));await page.locator('#product-save').click();await expect(page.locator('#product-save')).toBeEnabled();await expect(page.locator('#product-status')).toHaveText(await page.locator('[data-product-label=error]').textContent()??'');await page.unroute('**/cpanel/api/html-preview');await save();
  expect(errors).toEqual([]);expect((await pool.query('SELECT count(*) FROM products')).rows[0].count).toBe(before);
 }finally{await page.goto('about:blank').catch(()=>{});await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});

test('Products view permission and read-only capabilities',async({page,context,baseURL})=>{
 const user=await bootstrapSuperuser({name:'Product viewer',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id);
 try{
  const anonymous=await page.goto('/cpanel/products');expect(new URL(page.url()).pathname).toBe('/cpanel/login');
  await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[user.id]);
  await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'}]);
  expect((await page.goto('/cpanel/products'))?.status()).toBe(403);
  await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'products.view','true')",[user.id]);
  expect((await page.goto('/cpanel/products'))?.status()).toBe(200);await expect(page.locator('#product-add')).toBeDisabled();await page.locator('.product-card').first().locator('[data-bs-toggle]').click();await page.locator('.product-card').first().locator('.dropdown-item').click();await expect(page.locator('#product-name')).toBeDisabled();await expect(page.locator('#product-visible')).toBeDisabled();await expect(page.locator('#product-save')).toBeDisabled();
 }finally{await page.goto('about:blank').catch(()=>{});await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});
