import {sourceBrowserFixture} from './fixtures/source-browser.js';
import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {pool} from '../src/database/pool.js';
import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';
import {sessions} from '../src/cpanel/auth/sessions.js';
test('real Source Products UI, URL filters, pagination, details and Grid/List',async({page,context,baseURL})=>{
 const fixture=await sourceBrowserFixture(pool);const user=await bootstrapSuperuser({name:'Source activation test',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id);
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto('/cpanel/source-products?vendor='+fixture.vendors[0]);await expect(page.locator('#source-results-count')).toHaveText('15');await expect(page.locator('.source-card')).toHaveCount(12);await page.locator('#source-next').click();await expect(page.locator('#source-page')).toHaveText('2 / 2');await page.locator('[data-source-view=list]').click();await page.reload();await expect(page.locator('#source-page')).toHaveText('2 / 2');await expect(page.locator('#source-products-page')).toHaveAttribute('data-view','list');
  await page.locator('#source-search-field').selectOption('barcode');await page.locator('#source-search').fill('000123');await expect(page.locator('#source-page')).toHaveText('1 / 2');await page.locator('#source-filters-toggle').click();await page.locator('#source-filter-connection').selectOption('has');await expect(page.locator('#source-results-count')).toHaveText('1');await expect(page.locator('.source-card')).toContainText('2');await page.locator('[data-source-details]').click();await expect(page.locator('#source-pane-basic')).toContainText('12.345678');await page.locator('[data-source-tab=stock]').click();await expect(page.locator('#source-pane-stock tbody tr')).toHaveCount(2);await expect(page.locator('#source-pane-stock dd')).toHaveText('5');await page.locator('[data-source-tab=barcodes]').click();await expect(page.locator('#source-pane-barcodes li')).toHaveText(['000123','000124']);await page.locator('[data-source-tab=products]').click();await expect(page.locator('#source-pane-products dd')).toHaveText('2');await page.locator('#source-dialog .modal-footer button').click();
  await page.reload();await expect(page.locator('#source-results-count')).toHaveText('1');await expect(page.locator('#source-search')).toHaveValue('000123');await page.locator('#source-clear').click();await expect(page.locator('#source-search')).toHaveValue('000123');await expect(page.locator('#source-results-count')).not.toHaveText('1');await page.waitForFunction(()=>!new URL(location.href).searchParams.has('vendor'));await page.goBack();await expect(page.locator('#source-results-count')).toHaveText('1');
  await page.evaluate(()=>document.documentElement.dataset.bsTheme='dark');await page.screenshot({path:'artifacts/source-products-real.png'});expect(errors).toEqual([]);
 }finally{await page.goto('about:blank').catch(()=>{});await fixture.cleanup();await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});
test('Source Products requires view permission only; no source mutation routes',async({page,context,baseURL})=>{
 const user=await bootstrapSuperuser({name:'Source viewer '+randomUUID(),email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id);
 try{
  await page.goto('/cpanel/source-products');expect(new URL(page.url()).pathname).toBe('/cpanel/login');await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[user.id]);
  await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'}]);
  expect((await page.goto('/cpanel/source-products'))?.status()).toBe(403);for(const path of ['/cpanel/api/source-products','/cpanel/api/source-products/options?kind=vendor','/cpanel/api/source-products/1'])expect(await page.evaluate(async path=>(await fetch(path)).status,path)).toBe(403);await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'source_products.view','true')",[user.id]);expect((await page.goto('/cpanel/source-products'))?.status()).toBe(200);await expect(page.locator('.source-card')).toHaveCount(12);await page.locator('[data-source-details]').first().click();await expect(page.locator('#source-dialog')).toBeVisible();
  expect((await page.request.post('/cpanel/source-products',{data:{name:'Blocked'}})).status()).toBe(404);
 }finally{await page.goto('about:blank').catch(()=>{});await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});
test('Vendor autocomplete commits IDs, combines filters and shows consistent semantic states',async({page,context,baseURL})=>{
 const fixture=await sourceBrowserFixture(pool);const user=await bootstrapSuperuser({name:'Autocomplete test',email:randomUUID()+'@example.invalid',password:randomUUID()}),session=await sessions.create(user.id);
 await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
 try{
  await page.goto('/cpanel/source-products');await page.locator('#source-filters-toggle').click();const input=page.locator('#source-filter-vendor');const control=page.locator('#source-filter-vendor-control');
  await input.click();await expect(control.locator('[role=option]').first()).toBeVisible();await input.fill(fixture.prefix);await expect(control.locator('[role=option]')).toHaveCount(2);await input.press('ArrowDown');await input.press('Enter');await expect(page.locator('#source-results-count')).toHaveText('15');expect(new URL(page.url()).searchParams.get('vendor')).toBe(fixture.vendors[0]);
  await page.locator('#source-search').fill(fixture.prefix);await page.locator('#source-filter-stock').selectOption('out');await page.locator('#source-filter-active').selectOption('inactive');await expect(page.locator('#source-results-count')).toHaveText('1');
  for(const view of ['grid','list']){await page.locator('[data-source-view='+view+']').click();await expect(page.locator('.source-card')).toHaveClass(/is-inactive/);await expect(page.locator('.badge.source-status')).toHaveText('Inactive');await expect(page.locator('.source-stock strong')).toHaveText('-4');await expect(page.locator('.source-stock-state')).toHaveText('Out of stock');await expect(page.locator('.source-connection')).toHaveText('No storefront Product');}
  await page.locator('#source-filter-stock').selectOption('');await page.locator('#source-filter-active').selectOption('');await input.click();await input.fill(fixture.prefix);await expect(control.locator('[role=option]')).toHaveCount(2);await control.locator('[role=option]').nth(1).click();await expect(page.locator('#source-results-count')).toHaveText('1');expect(new URL(page.url()).searchParams.get('vendor')).toBe(fixture.vendors[1]);await expect(page.locator('.badge.source-status')).toHaveText('Active');await expect(page.locator('.source-stock-state')).toHaveText('In stock');await expect(page.locator('.source-connection')).toContainText('2');
  await page.reload();await page.locator('#source-filters-toggle').click();await expect(input).not.toHaveValue(fixture.vendors[1]);await expect(input).toHaveValue(new RegExp(fixture.prefix));await control.locator('[data-ac-clear]').click();await expect(page.locator('#source-results-count')).toHaveText('16');
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.bsTheme=theme,theme);await input.click();await expect(control.locator('[data-ac-panel]')).toBeVisible();await page.screenshot({path:'artifacts/source-autocomplete-'+theme+'.png'});await input.press('Escape');await page.locator('[data-source-view=grid]').click();await page.screenshot({path:'artifacts/source-status-grid-'+theme+'.png'});}
 }finally{await page.goto('about:blank');await fixture.cleanup();await pool.query('DELETE FROM cpanel_users WHERE id=$1',[user.id]);}
});
test('shared autocomplete debounce, stale replies, pagination, hydration, errors and modes',async({page})=>{
 await page.goto('/cpanel/login');
 await page.evaluate(async()=>{
  const url='/public/cpanel/js/content/async-autocomplete.js';const {AsyncAutocomplete}=await import(url);
  const root=document.createElement('div');root.id='test-ac';root.dataset.placeholder='All';root.innerHTML='<input data-ac-input role="combobox"><button data-ac-clear>Clear</button><div data-ac-panel hidden><div role="listbox" id="test-options"></div><span data-ac-status></span><button data-ac-retry hidden>Retry</button><button data-ac-more hidden>More</button></div><span hidden data-ac-label="loading">Loading</span><span hidden data-ac-label="empty">Empty</span><span hidden data-ac-label="failed">Failed</span>';document.body.prepend(root);
  const state:any={calls:[],changes:[],fail:true};(window as any).acState=state;
  state.control=new AsyncAutocomplete(root,{fetchPage:async({query,page}:any)=>{state.calls.push({query,page});if(query==='slow')await new Promise(resolve=>setTimeout(resolve,650));if(query==='error'&&state.fail)throw Error();return {options:query==='empty'?[]:[{value:query+page,label:(query||'Initial')+page,secondaryText:'Secondary'}],hasMore:page===1,nextPage:2};},hydrate:async(value:string)=>{await new Promise(resolve=>setTimeout(resolve,30));return {value,label:'Hydrated '+value};},onChange:(option:any)=>state.changes.push(option?.value??'')});
 });
 const root=page.locator('#test-ac'),input=root.locator('input'),options=root.locator('[role=option]');await input.click();await expect(options).toHaveText(['Initial1Secondary']);await root.locator('[data-ac-more]').click();await expect(options).toHaveCount(2);
 await input.fill('s');await input.fill('su');await input.fill('sup');await expect(options).toHaveText(['sup1Secondary']);expect(await page.evaluate(()=>(window as any).acState.calls.filter((c:any)=>['s','su'].includes(c.query)))).toEqual([]);
 await input.fill('slow');await page.waitForFunction(()=>(window as any).acState.calls.some((c:any)=>c.query==='slow'));await input.fill('fast');await expect(options).toHaveText(['fast1Secondary']);await page.waitForTimeout(700);await expect(options).toHaveText(['fast1Secondary']);
 await input.press('ArrowUp');await input.press('Enter');await expect(input).toHaveValue('fast1');expect(await page.evaluate(()=>(window as any).acState.changes)).toEqual(['fast1']);await root.locator('[data-ac-clear]').click();await expect(input).toHaveValue('');
 await page.evaluate(()=>(window as any).acState.control.setValue('123'));await expect(input).toHaveValue('Hydrated 123');await input.click();await input.fill('empty');await expect(root.locator('[data-ac-status]')).toHaveText('Empty');await input.fill('error');await expect(root.locator('[data-ac-status]')).toHaveText('Failed');await page.evaluate(()=>(window as any).acState.fail=false);await root.locator('[data-ac-retry]').click();await expect(options).toHaveText(['error1Secondary']);await input.press('Escape');await expect(input).toHaveValue('Hydrated 123');await expect(root.locator('[data-ac-panel]')).toBeHidden();
 await page.evaluate(()=>{const control=(window as any).acState.control;control.readOnly=true;control.input.readOnly=true;control.open();});await expect(root.locator('[data-ac-panel]')).toBeHidden();
 await page.evaluate(async()=>{const state=(window as any).acState;state.control.readOnly=false;state.control.input.readOnly=false;await state.control.setValue('');state.control.required=true;state.control.updateClear();});await input.fill('uncommitted');expect(await input.evaluate((el:any)=>el.checkValidity())).toBe(false);await expect(root.locator('[data-ac-clear]')).toBeHidden();await input.press('Escape');
});
