import {test,expect} from '@playwright/test';import {randomUUID} from 'node:crypto';
import {pool} from '../src/database/pool.js';import {bootstrapSuperuser} from '../src/cpanel/auth/bootstrap.js';import {sessions} from '../src/cpanel/auth/sessions.js';import {VendorCredentials} from '../src/vendors/credentials.js';import {config} from '../src/config/env.js';
const credentials=new VendorCredentials(config.vendors.credentialsKey);
for(const language of ['tm','ru','en'])test(`Vendors ${language}: real encrypted CRUD, safe reads, status/runtime preservation, responsive UI`,async({page,context,baseURL})=>{
 test.setTimeout(90000);let id='';const prefix='vendor-ui-'+randomUUID();
 try{
  id=(await bootstrapSuperuser({name:'Vendor UI',email:randomUUID()+'@example.invalid',password:randomUUID()})).id;const session=await sessions.create(id);await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:language,url:baseURL!}]);
  const translations=(await pool.query('SELECT * FROM interface_translations')).rows,t=(key:string)=>translations.find(r=>r.language_code===language&&r.translation_key===key).translation_value;
  const supplierTraffic:string[]=[];page.on('request',r=>{if(new URL(r.url()).hostname.endsWith('.invalid'))supplierTraffic.push(r.url());});
  expect((await page.goto('/cpanel/vendors'))?.status()).toBe(200);await expect(page.locator('#vendors-field')).toHaveValue('name');await expect(page.locator('#vendors-status')).toHaveValue('active');await page.locator('#vendors-search').fill(prefix);await expect(page.locator('#vendors-empty')).toBeVisible();
  await page.locator('[data-vendor-action=add]').click();await page.locator('#vendor-save').click();await expect(page.locator('#vendor-notice')).toHaveText(t('cpanel.vendors.invalidName'));
  await page.locator('#vendor-name').fill(prefix);await page.locator('#vendor-url').fill('https://'+prefix+'.example.invalid/catalog');await page.locator('#vendor-username').fill(prefix+'reader');await page.locator('#vendor-save').click();await expect(page.locator('#vendor-notice')).toHaveText(t('cpanel.vendors.passwordRequired'));
  const secret='first-secret-'+randomUUID();await page.locator('#vendor-password').fill(secret);await page.locator('[data-password-toggle]').click();await expect(page.locator('#vendor-password')).toHaveAttribute('type','text');await page.locator('#vendor-save').click();await expect(page.locator('#vendors-feedback')).toHaveText(t('cpanel.vendors.created'));await expect(page.locator('#vendor-dialog')).not.toBeVisible();await expect(page.locator('.vendor-item')).toHaveCount(1);
  let stored=(await pool.query('SELECT * FROM vendors WHERE name=$1',[prefix])).rows[0];const vendorId=stored.id,originalCiphertext=stored.password_encrypted;expect(credentials.decryptSecret(originalCiphertext)===secret).toBe(true);expect(stored.last_sequence).toBeNull();expect(stored.date_last_sync).toBeNull();await expect(page.locator('[data-value=healthLabel]')).toHaveText(t('cpanel.vendors.notSynced'));
  const open=async(action:string)=>{await page.locator('.vendor-item [data-bs-toggle=dropdown]').click();await page.locator('.vendor-item [data-vendor-action='+action+']').click();await expect(page.locator('#vendor-dialog')).toBeVisible();await expect(page.locator('#vendor-dialog-title')).not.toHaveText(t('cpanel.media.working'));await expect(page.locator('[data-vendor-section="'+(action==='edit'?'editor':action)+'"]')).toBeVisible();await page.waitForFunction(()=>getComputedStyle(document.querySelector('#vendor-dialog')!).opacity==='1');};
  await open('edit');await expect(page.locator('#vendor-password')).toHaveValue('');await expect(page.locator('#vendor-password-state')).toHaveText(t('cpanel.vendors.configured'));await page.locator('#vendor-username').fill(prefix+'changed');await page.locator('#vendor-save').click();await expect(page.locator('#vendors-feedback')).toHaveText(t('cpanel.vendors.updated'));expect((await pool.query('SELECT password_encrypted FROM vendors WHERE id=$1',[vendorId])).rows[0].password_encrypted===originalCiphertext).toBe(true);
  await open('edit');await page.locator('#vendor-password').fill('replacement-'+prefix);await page.locator('#vendor-save').click();await expect(page.locator('#vendor-dialog')).not.toBeVisible();stored=(await pool.query('SELECT * FROM vendors WHERE id=$1',[vendorId])).rows[0];expect(credentials.decryptSecret(stored.password_encrypted)==='replacement-'+prefix).toBe(true);
  for(const url of ['/cpanel/api/vendors?query='+prefix,'/cpanel/api/vendors/'+vendorId,'/cpanel/vendors']){const text=await (await context.request.get(url,{headers:{Cookie:(process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel')+'='+session.token}})).text();for(const sensitive of [secret,stored.password_encrypted,config.vendors.credentialsKey,'password_encrypted'])expect(text.includes(sensitive)).toBe(false);}
  const opaque='checkpoint-'+randomUUID().repeat(4);await pool.query("UPDATE vendors SET last_sequence=$2,date_last_sync='2026-09-16T10:00:00Z',date_last_operation='2026-09-16T10:00:03Z' WHERE id=$1",[vendorId,opaque]);
  await open('details');await expect(page.locator('[data-detail=lastSequence]')).toHaveText(opaque);await expect(page.locator('[data-detail=lastSync]')).not.toHaveText('—');await expect(page.locator('[data-detail=lastOperation]')).not.toHaveText('—');await expect(page.locator('[data-detail=lag]')).toHaveText('3 '+t('cpanel.vendors.seconds'));await expect(page.locator('[data-detail=healthLabel]')).toHaveText(t('cpanel.vendors.healthPending'));await page.locator('#vendor-dialog .btn-close').click();
  await open('status');await page.locator('#vendor-save').click();await expect(page.locator('#vendors-feedback')).toHaveText(t('cpanel.vendors.deactivated'));await expect(page.locator('.vendor-item')).toHaveCount(0);await page.locator('#vendors-status').selectOption('inactive');await expect(page.locator('.vendor-item')).toHaveCount(1);
  stored=(await pool.query('SELECT * FROM vendors WHERE id=$1',[vendorId])).rows[0];expect(stored.last_sequence).toBe(opaque);expect(credentials.decryptSecret(stored.password_encrypted)==='replacement-'+prefix).toBe(true);
  await open('status');await page.locator('#vendor-save').click();await expect(page.locator('#vendors-feedback')).toHaveText(t('cpanel.vendors.activated'));await page.locator('#vendors-status').selectOption('all');await expect(page.locator('.vendor-item')).toHaveCount(1);
  for(const [field,query] of [['name',prefix],['url',prefix+'.example.invalid'],['username',prefix+'changed'],['all',prefix+'changed']]){await page.locator('#vendors-field').selectOption(field);await page.locator('#vendors-search').fill(query);await expect(page.locator('.vendor-item')).toHaveCount(1);}
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.bsTheme=theme,theme);for(const view of ['grid','list']){await page.locator('[data-vendors-view='+view+']').click();await expect(page.locator('#vendors-field')).toHaveValue('all');await expect(page.locator('#vendors-status')).toHaveValue('all');for(const width of [1440,375]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);await page.screenshot({path:`artifacts/vendors-active-${language}-${theme}-${view}-${width}.png`,fullPage:true,animations:'disabled'});}}}
  for(const theme of ['light','dark'])for(const width of [1440,375]){await page.setViewportSize({width,height:900});await page.evaluate(theme=>document.documentElement.dataset.bsTheme=theme,theme);for(const action of ['edit','details']){await open(action);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);await page.screenshot({path:`artifacts/vendors-active-${language}-${theme}-${action}-${width}.png`,animations:'disabled'});await page.locator('#vendor-dialog .btn-close').click();await expect(page.locator('#vendor-dialog')).not.toBeVisible();}}
  expect(supplierTraffic).toEqual([]);expect(await page.locator('body').innerText()).not.toMatch(/cpanel\.vendors\./);await expect(page.locator('[data-navigation-id=sourceProducts]')).toHaveAttribute('data-availability','disabled');
  await Promise.all([page.waitForNavigation({waitUntil:'load'}),page.locator('#shell-language').selectOption(language==='en'?'ru':'en')]);await expect(page.locator('h1')).toHaveText(translations.find(r=>r.language_code===(language==='en'?'ru':'en')&&r.translation_key==='cpanel.navigation.vendors').translation_value);await page.goto('about:blank');
 }finally{await pool.query('DELETE FROM vendors WHERE name=$1',[prefix]);if(id)await pool.query('DELETE FROM cpanel_users WHERE id=$1',[id]);}
});

test('Vendors HTTP: independent strict grants, CSRF, runtime injection, safe payload and revocation',async({page,context,baseURL})=>{
 let id='';const prefix='vendor-http-'+randomUUID();const created:string[]=[];
 try{
  expect((await context.request.get('/cpanel/vendors',{maxRedirects:0})).status()).toBe(303);
  id=(await bootstrapSuperuser({name:'Vendor HTTP',email:randomUUID()+'@example.invalid',password:randomUUID()})).id;const session=await sessions.create(id);const headers={Cookie:(process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel')+'='+session.token,'X-CSRF-Token':session.session.csrf_token};
  const input={name:prefix,url:'http://127.0.0.1:9/couchdb',username:'reader',password:'do-not-return'};
  const post=()=>context.request.post('/cpanel/api/vendors',{headers,data:input});const first=await post();expect(first.status()).toBe(201);const target=(await first.json()).row.id;created.push(target);
  await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[id]);
  const calls={view:()=>context.request.get('/cpanel/api/vendors',{headers}),create:post,update:()=>context.request.patch('/cpanel/api/vendors/'+target,{headers,data:{...input,password:''}}),status:()=>context.request.post('/cpanel/api/vendors/'+target+'/status',{headers,data:{status:'inactive'}})};
  for(const permission of Object.keys(calls))for(const value of [undefined,false,'true',1,true]){
   await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[id]);if(value!==undefined)await pool.query('INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,$2,$3::jsonb)',[id,'vendors.'+permission,JSON.stringify(value)]);
   for(const [key,call] of Object.entries(calls)){const response=await call();expect(response.status()).toBe(value===true&&permission===key?(key==='create'?201:200):403);if(response.status()===201)created.push((await response.json()).row.id);}
  }
  await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[id]);await pool.query("INSERT INTO cpanel_user_permissions(user_id,key,value) VALUES($1,'superuser','true')",[id]);
  const before=JSON.stringify((await pool.query('SELECT * FROM vendors WHERE id=$1',[target])).rows);
  for(const bad of ['', 'bad'])for(const op of ['create','update','status']){const options={headers:{...headers,'X-CSRF-Token':bad},data:op==='status'?{status:'active'}:input};const response=op==='create'?await context.request.post('/cpanel/api/vendors',options):op==='update'?await context.request.patch('/cpanel/api/vendors/'+target,options):await context.request.post('/cpanel/api/vendors/'+target+'/status',options);expect(response.status()).toBe(403);}
  for(const field of ['last_sequence','date_last_sync','date_last_operation','sync_health','password_encrypted']){expect((await context.request.patch('/cpanel/api/vendors/'+target,{headers,data:{...input,[field]:'injected'}})).status()).toBe(400);expect((await context.request.post('/cpanel/api/vendors',{headers,data:{...input,[field]:'injected'}})).status()).toBe(400);}
  expect(JSON.stringify((await pool.query('SELECT * FROM vendors WHERE id=$1',[target])).rows)===before).toBe(true);
  await context.addCookies([{name:headers.Cookie.split('=')[0],value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'}]);const registryTarget=(await bootstrapSuperuser({name:'Registry target',email:randomUUID()+'@example.invalid',password:randomUUID()})).id;
  try{await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[registryTarget]);await page.goto('/cpanel/permissions/'+registryTarget);for(const key of ['vendors.view','vendors.create','vendors.update','vendors.status'])await expect(page.locator('[data-permission-key="'+key+'"]')).toBeEnabled();}finally{await pool.query('DELETE FROM cpanel_users WHERE id=$1',[registryTarget]);}
  await pool.query("UPDATE cpanel_user_permissions SET key='vendors.view' WHERE user_id=$1",[id]);await page.goto('/cpanel/vendors');for(const action of ['add','edit','status'])await expect(page.locator('[data-vendor-action='+action+']')).toHaveCount(0);await pool.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[id]);expect((await page.goto('/cpanel/vendors'))?.status()).toBe(403);
 }finally{await pool.query('DELETE FROM vendors WHERE name=$1',[prefix]);if(id)await pool.query('DELETE FROM cpanel_users WHERE id=$1',[id]);}
});

test('Vendors server search: stale responses, failure retry, pagination and safe queries',async({page,context,baseURL})=>{
 let id='';const prefix='vendor-search-'+randomUUID();
 try{
  for(let i=0;i<12;i++)await pool.query('INSERT INTO vendors(name,url,username,password_encrypted) VALUES($1,$2,$3,$4)',[prefix+' '+i,'https://example.invalid/db','reader',credentials.encryptSecret('fixture')]);
  id=(await bootstrapSuperuser({name:'Search',email:randomUUID()+'@example.invalid',password:randomUUID()})).id;const session=await sessions.create(id);await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'}]);await page.goto('/cpanel/vendors');await page.locator('#vendors-search').fill(prefix);await expect(page.locator('.vendor-item')).toHaveCount(9);await page.locator('[data-vendor-page=next]').click();await expect(page.locator('.vendor-item')).toHaveCount(3);
  await page.route('**/cpanel/api/vendors?**',async route=>{if(new URL(route.request().url()).searchParams.get('query')===prefix+' slow'){await new Promise(resolve=>setTimeout(resolve,800));await route.fulfill({json:{success:true,rows:[],total:0,page:1}});}else await route.continue();});
  await page.locator('#vendors-search').fill(prefix+' slow');await page.waitForTimeout(400);await page.locator('#vendors-search').fill(prefix);await expect(page.locator('.vendor-item')).toHaveCount(9);await page.waitForTimeout(900);await expect(page.locator('.vendor-item')).toHaveCount(9);await page.unroute('**/cpanel/api/vendors?**');
  await page.route('**/cpanel/api/vendors?**',route=>route.abort());await page.locator('#vendors-search').fill(prefix+' failed');await expect(page.locator('#vendors-feedback')).not.toBeEmpty();await page.unroute('**/cpanel/api/vendors?**');await page.locator('#vendors-search').fill(prefix);await expect(page.locator('#vendors-feedback')).toBeEmpty();
 }finally{await pool.query('DELETE FROM vendors WHERE name LIKE $1',[prefix+'%']);if(id)await pool.query('DELETE FROM cpanel_users WHERE id=$1',[id]);}
});

test('Vendor save failure preserves safe input, clears password and permits retry without duplicate writes',async({page,context,baseURL})=>{
 let id='';const name='vendor-retry-'+randomUUID();
 try{
  id=(await bootstrapSuperuser({name:'Retry',email:randomUUID()+'@example.invalid',password:randomUUID()})).id;const session=await sessions.create(id);await context.addCookies([{name:process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel',value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'}]);
  await page.goto('/cpanel/vendors');await page.locator('[data-vendor-action=add]').click();await page.locator('#vendor-name').fill(name);await page.locator('#vendor-url').fill('https://example.invalid/db');await page.locator('#vendor-username').fill('reader');await page.locator('#vendor-password').fill('retry-secret');
  let posts=0;await page.route('**/cpanel/api/vendors',async route=>{posts++;await new Promise(resolve=>setTimeout(resolve,200));await route.fulfill({status:500,json:{success:false,code:'VENDOR_CREATE_FAILED'}});});
  await page.locator('#vendor-save').click();await expect(page.locator('#vendor-save')).toBeDisabled();await expect(page.locator('#vendor-notice')).toBeVisible();await expect(page.locator('#vendor-name')).toHaveValue(name);await expect(page.locator('#vendor-password')).toHaveValue('');expect(posts).toBe(1);expect((await pool.query('SELECT 1 FROM vendors WHERE name=$1',[name])).rowCount).toBe(0);
  await page.unroute('**/cpanel/api/vendors');await page.locator('#vendor-password').fill('retry-secret');await page.locator('#vendor-save').click();await expect(page.locator('#vendor-dialog')).not.toBeVisible();expect((await pool.query('SELECT 1 FROM vendors WHERE name=$1',[name])).rowCount).toBe(1);
 }finally{await pool.query('DELETE FROM vendors WHERE name=$1',[name]);if(id)await pool.query('DELETE FROM cpanel_users WHERE id=$1',[id]);}
});

test('replacement failure UI retains credential A and excludes secrets from validation/error/read responses',async({page,context,baseURL})=>{
 const failureName='vendor_review_fail_'+randomUUID().replaceAll('-','');let actor='';const name='vendor-replacement-review-'+randomUUID(),secretA=randomUUID(),secretB=randomUUID();
 try{
  actor=(await bootstrapSuperuser({name:'Replacement review',email:randomUUID()+'@example.invalid',password:randomUUID()})).id;const session=await sessions.create(actor),cookieName=process.env.TEST_PRODUCTION==='1'?'__Secure-hormat_cpanel':'hormat_cpanel';
  await context.addCookies([{name:cookieName,value:session.token,domain:new URL(baseURL!).hostname,path:'/cpanel',secure:process.env.TEST_PRODUCTION==='1',httpOnly:true,sameSite:'Lax'},{name:'hormat_lang',value:'en',url:baseURL!}]);
  const encrypted=credentials.encryptSecret(secretA);const id=(await pool.query('INSERT INTO vendors(name,url,username,password_encrypted) VALUES($1,$2,$3,$4) RETURNING id',[name,'https://example.invalid/db','reader',encrypted])).rows[0].id;
  const safe=(text:string)=>{for(const secret of [secretA,secretB,encrypted,config.vendors.credentialsKey])expect(text.includes(secret)).toBe(false);};
  const headers={Cookie:cookieName+'='+session.token,'X-CSRF-Token':session.session.csrf_token};
  const invalid=await context.request.patch('/cpanel/api/vendors/'+id,{headers,data:{name:'',url:'https://example.invalid/db',username:'reader',password:secretB}});expect(invalid.status()).toBe(400);safe(await invalid.text());
  await page.goto('/cpanel/vendors');await page.locator('#vendors-search').fill(name);await expect(page.locator('.vendor-item')).toHaveCount(1);await page.locator('.vendor-item [data-bs-toggle=dropdown]').click();await page.locator('[data-vendor-action=edit]').click();await expect(page.locator('#vendor-password')).toHaveValue('');await expect(page.locator('#vendor-save')).toBeEnabled();safe(await page.content());
  // Disposable trigger affects only this fixture; all other Vendors remain writable.
  await pool.query(`CREATE FUNCTION ${failureName}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id=${BigInt(id)} THEN RAISE EXCEPTION 'Injected Vendor update failure'; END IF; RETURN NEW; END $$`);
  await pool.query(`CREATE TRIGGER ${failureName} BEFORE UPDATE ON vendors FOR EACH ROW EXECUTE FUNCTION ${failureName}()`);
  const failedResponse=page.waitForResponse(response=>response.url().endsWith('/cpanel/api/vendors/'+id)&&response.request().method()==='PATCH');
  await page.locator('#vendor-password').fill(secretB);await page.locator('#vendor-save').click();const message=(await pool.query("SELECT translation_value FROM interface_translations WHERE language_code='en' AND translation_key='cpanel.vendors.updateFailed'")).rows[0].translation_value;await expect(page.locator('#vendor-notice')).toHaveText(message);const failed=await failedResponse;expect(failed.status()).toBe(500);const failureBody=await failed.text();safe(failureBody);expect(JSON.stringify(JSON.parse(failureBody))===JSON.stringify({success:false,code:'VENDOR_UPDATE_FAILED'})).toBe(true);await expect(page.locator('#vendor-password')).toHaveValue('');safe(await page.content());
  const current=(await pool.query('SELECT password_encrypted FROM vendors WHERE id=$1',[id])).rows[0].password_encrypted;expect(current===encrypted).toBe(true);expect(credentials.decryptSecret(current)===secretA).toBe(true);
 }finally{await pool.query(`DROP TRIGGER IF EXISTS ${failureName} ON vendors`);await pool.query(`DROP FUNCTION IF EXISTS ${failureName}()`);await pool.query('DELETE FROM vendors WHERE name=$1',[name]);if(actor)await pool.query('DELETE FROM cpanel_users WHERE id=$1',[actor]);}
});
