import {productsApi} from './products-api.js';
import {productReferenceLookup} from '../../controllers/cpanel/product-reference-lookups.js';
import {productCreateLookup} from '../../controllers/cpanel/product-create-lookups.js';
import {sourceProductsQuery} from '../../controllers/cpanel/source-products-api.js';
import {sourceProductsPage} from '../../controllers/cpanel/source-products.js';
import {productsPage} from '../../controllers/cpanel/products.js';
import {htmlPreviewApi} from './html-preview-api.js';
import {settingsApi} from './settings-api.js';
import {settingsPage} from '../../controllers/cpanel/settings.js';
import {optionTypesApi} from './option-types-api.js';
import {optionTypes} from '../../controllers/cpanel/option-types.js';
import {interfaceTranslationsApi} from './interface-translations-api.js';
import {interfaceTranslationsPage} from '../../controllers/cpanel/interface-translations.js';
import {languagesApi} from './languages-api.js';
import {languagesPage} from '../../controllers/cpanel/languages.js';
import {currenciesApi} from './currencies-api.js';
import {frontendCurrencies,vendorCurrencies} from '../../controllers/cpanel/currencies.js';
import {discountsApi} from './discounts-api.js';
import {discounts} from '../../controllers/cpanel/discounts.js';
import {categoriesApi} from './categories-api.js';
import {categories} from '../../controllers/cpanel/categories.js';
import {brandsApi} from './brands-api.js';
import {brands} from '../../controllers/cpanel/brands.js';
import {vendorsApi} from './vendors-api.js';
import {vendors} from '../../controllers/cpanel/vendors.js';
import {mediaApi} from './media-api.js';
import { browseMedia, inspectMedia } from '../../controllers/cpanel/media-browser.js';
import { usersApi } from './users-api.js';
import { permissionsApi } from './permissions-api.js';
import { permissions, permissionDetail } from '../../controllers/cpanel/permissions.js';
import { users } from '../../controllers/cpanel/users.js';
import { Router, urlencoded } from 'express';
import { rateLimit } from 'express-rate-limit';
import { uploadMedia } from '../../controllers/cpanel/media.js';
import { shellContext } from '../../cpanel/shell/context.js';
import { profile, submitProfile, submitPassword, passwordLimited } from '../../controllers/cpanel/profile.js';
import { index } from '../../controllers/cpanel/index.js';
import { login, submitLogin, logout } from '../../controllers/cpanel/login.js';
import { loadCpanelAuth, requireCpanelAuth, requireCsrf, requirePermission } from '../../cpanel/auth/http.js';

export const cpanelRouter = Router();
const loginLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 30, standardHeaders: 'draft-8', legacyHeaders: false,
  handler: (_request, response) => { response.status(429).type('text').send(response.locals.t('cpanel.auth.tooManyAttempts')); },
});
cpanelRouter.use(loadCpanelAuth);
cpanelRouter.post('/media/upload', requireCpanelAuth, requireCsrf, uploadMedia);
cpanelRouter.get('/', requireCpanelAuth, shellContext, index);
const passwordLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: 'draft-8', legacyHeaders: false,
  keyGenerator: (_request, response) => response.locals.cpanelUser!.id, handler: passwordLimited,
});
cpanelRouter.post('/profile/password', requireCpanelAuth, urlencoded({ extended: false, limit: '16kb' }), requireCsrf, shellContext, passwordLimit, submitPassword);
cpanelRouter.post('/profile', requireCpanelAuth, urlencoded({ extended: false, limit: '8kb' }), requireCsrf, submitProfile);
cpanelRouter.use('/api/users',usersApi);
cpanelRouter.use('/api/media',mediaApi);
cpanelRouter.get('/api/media/details', requireCpanelAuth, requirePermission('media.view'), inspectMedia);
cpanelRouter.get('/media', requireCpanelAuth, requirePermission('media.view'), shellContext, browseMedia);
cpanelRouter.use('/api/vendors',vendorsApi);
cpanelRouter.use('/api/brands',brandsApi);
cpanelRouter.use('/api/products',productsApi);
cpanelRouter.use('/api/categories',categoriesApi);
cpanelRouter.use('/api/discounts',discountsApi);
cpanelRouter.use('/api/html-preview',htmlPreviewApi);
cpanelRouter.use('/api/settings',settingsApi);
cpanelRouter.get('/settings',requireCpanelAuth,requirePermission('settings.view'),shellContext,settingsPage);
cpanelRouter.use('/api/order-statuses',optionTypesApi('order-status'));
cpanelRouter.get('/order-statuses',requireCpanelAuth,requirePermission('order_statuses.view'),shellContext,optionTypes('order-status'));
cpanelRouter.use('/api/payment-types',optionTypesApi('payment'));
cpanelRouter.use('/api/delivery-types',optionTypesApi('delivery'));
cpanelRouter.get('/payment-types',requireCpanelAuth,requirePermission('payment_types.view'),shellContext,optionTypes('payment'));
cpanelRouter.get('/delivery-types',requireCpanelAuth,requirePermission('delivery_types.view'),shellContext,optionTypes('delivery'));
cpanelRouter.use('/api/interface-translations',interfaceTranslationsApi);
cpanelRouter.get('/interface-translations',requireCpanelAuth,requirePermission('interface_translations.view'),shellContext,interfaceTranslationsPage);
cpanelRouter.use('/api/languages',languagesApi);
cpanelRouter.get('/languages',requireCpanelAuth,requirePermission('languages.view'),shellContext,languagesPage);
cpanelRouter.get('/currencies/frontend', requireCpanelAuth, requirePermission('currencies.frontend.view'), shellContext, frontendCurrencies);
cpanelRouter.get('/currencies/vendors', requireCpanelAuth, requirePermission('currencies.vendor_rates.view'), shellContext, vendorCurrencies);
cpanelRouter.use('/api/currencies',currenciesApi);
cpanelRouter.get('/discounts', requireCpanelAuth, requirePermission('discounts.view'), shellContext, discounts);
cpanelRouter.get('/categories', requireCpanelAuth, requirePermission('categories.view'), shellContext, categories);
cpanelRouter.get('/api/source-products',requireCpanelAuth,requirePermission('source_products.view'),sourceProductsQuery('list'));
cpanelRouter.get('/api/source-products/options',requireCpanelAuth,requirePermission('source_products.view'),sourceProductsQuery('options'));
cpanelRouter.get('/api/source-products/:id',requireCpanelAuth,requirePermission('source_products.view'),sourceProductsQuery('details'));
cpanelRouter.get('/source-products',requireCpanelAuth,requirePermission('source_products.view'),shellContext,sourceProductsPage);
cpanelRouter.get('/api/product-references/brands',requireCpanelAuth,productReferenceLookup('brands'));
cpanelRouter.get('/api/product-references/categories',requireCpanelAuth,productReferenceLookup('categories'));
cpanelRouter.get('/api/product-create/vendors',requireCpanelAuth,requirePermission('products.create'),productCreateLookup('vendors'));
cpanelRouter.get('/api/product-create/sources',requireCpanelAuth,requirePermission('products.create'),productCreateLookup('sources'));
cpanelRouter.get('/products',requireCpanelAuth,requirePermission('products.view'),shellContext,productsPage);
cpanelRouter.get('/brands', requireCpanelAuth, requirePermission('brands.view'), shellContext, brands);
cpanelRouter.get('/vendors', requireCpanelAuth, requirePermission('vendors.view'), shellContext, vendors);
cpanelRouter.get('/users', requireCpanelAuth, requirePermission('users.view'), shellContext, users);
cpanelRouter.use('/api/permissions',permissionsApi);
cpanelRouter.get('/permissions', requireCpanelAuth, requirePermission('permissions.view'), shellContext, permissions);
cpanelRouter.get('/permissions/:userId', requireCpanelAuth, requirePermission('permissions.view'), shellContext, permissionDetail);
cpanelRouter.get('/profile', requireCpanelAuth, shellContext, profile);
cpanelRouter.get('/login', login);
cpanelRouter.post('/login', loginLimit, urlencoded({ extended: false, limit: '4kb' }), requireCsrf, submitLogin);
cpanelRouter.post('/logout', urlencoded({ extended: false, limit: '1kb' }), requireCpanelAuth, requireCsrf, logout);
