import {bulkDrafts} from '../../controllers/cpanel/product-bulk-drafts.js';
import {productAttachments} from '../../controllers/cpanel/product-attachments.js';
import {Router,json,type ErrorRequestHandler} from 'express';
import {requireCpanelAuth,requireCsrf} from '../../cpanel/auth/http.js';
import {productBrowserLookup,productsForSource,productRead,productMutate,productDiscountRelationship} from '../../controllers/cpanel/products-api.js';
export const productsApi=Router();
productsApi.use(requireCpanelAuth);
productsApi.get('/bulk-drafts/review',bulkDrafts('review'));
productsApi.get('/bulk-drafts/:token/status',bulkDrafts('status'));
productsApi.get('/bulk-drafts/:token',bulkDrafts('page'));
productsApi.get('/',productRead('list'));
productsApi.get('/discounts',productRead('discounts'));
productsApi.get('/source/:id/products',productsForSource);
productsApi.get('/source/:id',productRead('source'));
productsApi.get('/attachments/:kind/:parent',productAttachments());
productsApi.get('/browser-lookups/:kind',productBrowserLookup);
productsApi.get('/:id',productRead('details'));
productsApi.use(requireCsrf,json({limit:'512kb'}));
productsApi.post('/attachments/:kind/:parent/attach',productAttachments('attach'));
productsApi.post('/attachments/:kind/:parent/detach',productAttachments('detach'));
productsApi.post('/bulk-drafts/:token',bulkDrafts('start'));
productsApi.post('/',productMutate('create'));
productsApi.post('/:id/discounts/attach',productDiscountRelationship('attach'));
productsApi.post('/:id/discounts/detach',productDiscountRelationship('detach'));
for(const scope of ['basic','seo','description','visibility','priceRules','translations','gallery','discounts','preview'] as const)productsApi.post('/:id/'+scope,productMutate(scope));
const invalid:ErrorRequestHandler=(e,_req,res,next)=>{if(['entity.parse.failed','entity.too.large'].includes(e?.type)){res.status(400).json({success:false,code:'PRODUCT_INVALID_REQUEST'});return;}next(e);};
productsApi.use(invalid);
