import type {RequestHandler,Response} from 'express';
import {currenciesService,type CurrencyOperation} from '../../currencies/service.js';
import {CurrencyError} from '../../currencies/validation.js';
export const currencyActor=(response:Response)=>({id:response.locals.cpanelUser!.id,sessionHash:response.locals.cpanelSession!.token_hash});
function failure(response:Response,error:unknown){const e=error instanceof CurrencyError?error:new CurrencyError('CURRENCY_READ_FAILED',500);response.status(e.status).json({success:false,code:e.code});}
export const listFrontend:RequestHandler=async(request,response)=>{try{response.json({success:true,...await currenciesService.list(currencyActor(response),request.query)});}catch(error){failure(response,error);}};
export const detailFrontend:RequestHandler=async(request,response)=>{try{if(Object.keys(request.query).length)throw new CurrencyError('CURRENCY_INVALID_REQUEST');response.json({success:true,...await currenciesService.details(currencyActor(response),request.params.id as string)});}catch(error){failure(response,error);}};
export const mutateFrontend=(operation:CurrencyOperation):RequestHandler=>async(request,response)=>{const input=request.body;request.body=undefined;try{if(Object.keys(request.query).length)throw new CurrencyError('CURRENCY_INVALID_REQUEST');response.status(operation==='create'?201:200).json({success:true,...await currenciesService.mutate(currencyActor(response),operation,request.params.id as string|undefined,input)});}catch(error){failure(response,error);}};
export const listVendor:RequestHandler=async(request,response)=>{try{response.json({success:true,...await currenciesService.vendorList(currencyActor(response),request.query)});}catch(error){failure(response,error);}};
export const detailVendor:RequestHandler=async(request,response)=>{try{if(Object.keys(request.query).length)throw new CurrencyError('CURRENCY_INVALID_REQUEST');response.json({success:true,...await currenciesService.vendorDetails(currencyActor(response),request.params.vendor as string,request.params.id as string)});}catch(error){failure(response,error);}};
export const saveVendor:RequestHandler=async(request,response)=>{const input=request.body;request.body=undefined;try{if(Object.keys(request.query).length)throw new CurrencyError('CURRENCY_INVALID_REQUEST');response.json({success:true,...await currenciesService.saveVendorRate(currencyActor(response),request.params.vendor as string,request.params.id as string,input)});}catch(error){failure(response,error);}};
