import {VendorCredentials} from '../../src/vendors/credentials.js';
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import pg from 'pg';
import {config} from '../../src/config/env.js';
import {pool} from '../../src/database/pool.js';
import {migrate} from '../../src/database/migrate.js';
import {bootstrapSuperuser} from '../../src/cpanel/auth/bootstrap.js';
import {SessionRepository} from '../../src/cpanel/auth/sessions.js';
import {BrandsRepository,type BrandActor} from '../../src/brands/repository.js';
import {BrandsService} from '../../src/brands/service.js';
import {MediaBrowser} from '../../src/cpanel/media/browser.js';
const schema='brands_test_'+randomUUID().replaceAll('-',''),db=new pg.Pool({...config.database,options:`-c search_path=${schema}`}),repo=new BrandsRepository(db);
let root:BrandActor,other:BrandActor,normal:BrandActor,mediaRoot:string,service:BrandsService;
const pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8x8AAAAASUVORK5CYII=','base64');
async function actor(superuser:boolean){const user=await bootstrapSuperuser({name:'Brand test',email:randomUUID()+'@example.invalid',password:randomUUID()},db);if(!superuser)await db.query('DELETE FROM cpanel_user_permissions WHERE user_id=$1',[user.id]);return {id:user.id,sessionHash:(await new SessionRepository(db).create(user.id)).session.token_hash};}
const create=async(name='Brand '+randomUUID())=>(await service.mutate(root,'create',undefined,{name})).row.id;
const stored=async(id:string)=>(await db.query('SELECT * FROM brands WHERE id=$1',[id])).rows[0];
const gallery=async(id:string)=>(await db.query('SELECT media_reference,sort_order FROM brand_media WHERE brand_id=$1 ORDER BY sort_order',[id])).rows;
before(async()=>{await pool.query(`CREATE SCHEMA ${schema}`);await migrate(db);root=await actor(true);other=await actor(true);normal=await actor(false);mediaRoot=await mkdtemp(path.join(tmpdir(),'hormat-brands-'));for(const file of ['a.png','b.png','c.png'])await writeFile(path.join(mediaRoot,file),pixel);await mkdir(path.join(mediaRoot,'cache'));await writeFile(path.join(mediaRoot,'cache','temporary.png'),pixel);await writeFile(path.join(mediaRoot,'fake.png'),'not an image');await symlink('/etc/passwd',path.join(mediaRoot,'escape.png'));service=new BrandsService(repo,new MediaBrowser(mediaRoot));});
after(async()=>{await db.end();await pool.query(`DROP SCHEMA ${schema} CASCADE`);await pool.end();if(mediaRoot)await rm(mediaRoot,{recursive:true,force:true});});
test('SEO migration, canonical unique slug, independent field overrides, fallback and existing Brand scope',async()=>{
 const {contentText}=await import('../../src/public/cpanel/js/content/editor-state.js');
 const a=await create(),b=await create();assert.notEqual((await stored(a)).slug,(await stored(b)).slug);assert.equal((await stored(a)).is_visible,false);
 await service.mutate(root,'seo',a,{slug:' Example Brand ',seo_title:' Base SEO ',seo_description:' Base description '});
 assert.equal((await stored(a)).slug,'example-brand');assert.equal((await stored(a)).seo_title,'Base SEO');
 await assert.rejects(service.mutate(root,'seo',b,{slug:'EXAMPLE-BRAND'}),{code:'BRAND_SLUG_TAKEN'});
 for(const value of ['', 'a/b', '../bad','a--b','x'.repeat(121)])await assert.rejects(service.mutate(root,'seo',a,{slug:value}),{code:'BRAND_INVALID_SLUG'});
 await assert.rejects(service.mutate(root,'seo',a,{seo_title:'x'.repeat(201)}),{code:'BRAND_INVALID_SEO'});
 await service.mutate(root,'translations',a,{translations:{ru:'Имя'}});
 await service.mutate(root,'gallery',a,{original:[],items:['a.png']});const base=await stored(a),media=await gallery(a);
 await service.mutate(root,'translations',a,{field:'seo_title',translations:{ru:'Заголовок'}});
 await service.mutate(root,'translations',a,{field:'seo_description',translations:{en:'Description'}});
 let row=(await service.details(root,a)).row;assert.equal(row.translations.ru,'Имя');assert.equal(row.seoTranslations.seo_title.ru,'Заголовок');assert.equal(row.seoTranslations.seo_description.en,'Description');assert.equal(row.basic.name,base.name);assert.equal(row.seo.seo_title,base.seo_title);assert.deepEqual(await gallery(a),media);
 assert.equal(contentText(row.seo.seo_title,row.seoTranslations.seo_title.tm),'Base SEO');
 await service.mutate(root,'translations',a,{field:'seo_title',translations:{ru:'   '}});row=(await service.details(root,a)).row;assert.equal(contentText(row.seo.seo_title,row.seoTranslations.seo_title.ru),'Base SEO');assert.equal(row.translations.ru,'Имя');assert.equal(row.seoTranslations.seo_description.en,'Description');
 await service.mutate(root,'translations',a,{translations:{en:''}});assert.equal((await service.details(root,a)).row.seoTranslations.seo_description.en,'Description');
 await service.mutate(root,'basic',a,{name:'Renamed'});assert.equal((await service.details(root,a)).row.seoTranslations.seo_description.en,'Description');assert.deepEqual(await gallery(a),media);
 await assert.rejects(service.mutate(root,'translations',a,{field:'slug',translations:{en:'bad'}}),{code:'BRAND_INVALID_REQUEST'});
 await assert.rejects(service.mutate(normal,'seo',a,{seo_title:'denied'}),{code:'BRAND_FORBIDDEN'});
});
test('nullable products.brand_id FK and real count preserve source_product_id',async()=>{
 const vendor=(await db.query("INSERT INTO vendors(name,url,username,password_encrypted,is_active) VALUES('fixture','https://example.invalid/db','fixture',$1,false) RETURNING id",[new VendorCredentials(config.vendors.credentialsKey).encryptSecret('fixture')])).rows[0].id;
 const source=(await db.query("INSERT INTO source_products(vendor_id,source_id,name) VALUES($1,'seo-count','Count fixture') RETURNING id",[vendor])).rows[0].id;
 const a=await create(),b=await create();await db.query('INSERT INTO products(source_product_id,brand_id,name) VALUES($1,$2,\'Fixture Product\'),($1,$2,\'Fixture Product\'),($1,NULL,\'Fixture Product\')',[source,a]);
 assert.equal((await service.details(root,a)).row.productCount,2);assert.equal((await service.details(root,b)).row.productCount,0);
 assert.equal((await service.list(root,{})).rows.find(r=>r.id===a)?.productCount,2);
 await assert.rejects(db.query('INSERT INTO products(source_product_id,brand_id,name) VALUES($1,9223372036854775807,\'Fixture Product\')',[source]),{code:'23503'});
 assert.equal((await db.query('SELECT count(*) FROM products WHERE source_product_id=$1',[source])).rows[0].count,'3');
 assert.equal((await db.query("SELECT column_name FROM information_schema.columns WHERE table_schema=$1 AND table_name='brands' AND column_name='products_count'",[schema])).rowCount,0);
});
test('separate SEO mutation cannot overwrite Basic, Gallery or translations and Basic rejects SEO',async()=>{
 const id=await create('Basic');await service.mutate(root,'basic',id,{main_media_reference:'a.png',is_visible:true});await service.mutate(root,'gallery',id,{original:[],items:['a.png','b.png']});await service.mutate(root,'translations',id,{translations:{ru:'Имя'}});
 const base=await stored(id),media=await gallery(id);
 await service.mutate(root,'seo',id,{slug:'isolated-seo',seo_title:'Title',seo_description:'Description'});
 let result=await stored(id);for(const key of ['name','main_media_reference','is_visible'])assert.equal(result[key],base[key]);assert.deepEqual(await gallery(id),media);assert.equal((await service.details(root,id)).row.translations.ru,'Имя');
 await service.mutate(root,'basic',id,{name:'Changed',main_media_reference:null,is_visible:false});result=await stored(id);assert.equal(result.slug,'isolated-seo');assert.equal(result.seo_title,'Title');assert.equal(result.seo_description,'Description');
 await assert.rejects(service.mutate(root,'basic',id,{seo_title:'wrong scope'}),{code:'BRAND_INVALID_REQUEST'});await assert.rejects(service.mutate(root,'seo',id,{name:'wrong scope'}),{code:'BRAND_INVALID_REQUEST'});await assert.rejects(service.mutate(normal,'seo',id,{seo_title:'denied'}),{code:'BRAND_FORBIDDEN'});
});
